### ISSUE TITLE
Training won't start

### ISSUE THREAD

**Issue by DiggyDre** [derrian-distro/LoRA_Easy_Training_Scripts#101]
I am looking for something other than Kohya because I have no clue what they changed. I recently rebuilt my PC, reinstalled Windows, and I haven't been able to train decent models with Kohya since then... all of the hands suck beyond what I was able to accomplish before. Anyways, I really want to give your setup a shot but I keep running into this:

starting validation of args...
starting validation of dataset_args...
validated, starting training...
Loading settings from runtime_store\config.toml...
Traceback (most recent call last):
  File "D:\AI\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 871, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "D:\AI\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 2573, in read_config_from_file
    config_dict = toml.load(f)
  File "D:\AI\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "D:\AI\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 260, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: ':'. Try quoting the key name. (line 12 column 6 char 331)
Failed to train because of error:
Command '['D:\\AI\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment]
unfortunately for you, I'm also using kohya, so you will probably want to look elsewhere.

that being said, seems like there is an error in the toml that gets generated, likely because of file paths. I can't tell you more as the trace isn't very helpful
