### ISSUE TITLE
No module named 'accelerate'

### ISSUE THREAD

**Issue by Zovya** [derrian-distro/LoRA_Easy_Training_Scripts#103]
starting validation of args...
starting validation of dataset_args...
validated, starting training...
Traceback (most recent call last):
  File "/home/v/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 14, in <module>
    from accelerate.utils import set_seed
ModuleNotFoundError: No module named 'accelerate'
Failed to train because of error:
Command '['/home/v/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python', 'sd_scripts/train_network.py', '--config_file=runtime_store/config.toml', '--dataset_config=runtime_store/dataset.toml']' returned non-zero exit status 1.

I'll note that the required tensorflow and xformers weren't available and I had to manually install the latest.

**Comment by derrian-distro** [comment]
what system are you using? I assume some linux based system, as I know the windows installer doesn't have issues with those

**Comment by Zovya** [comment]
> what system are you using? I assume some linux based system, as I know the windows installer doesn't have issues with those

yes. sorry for the late reply. got distracted. I'm using an arch-based linux manjaro
