### ISSUE TITLE
Can't recognize display

### ISSUE THREAD

**Issue by lIlIlI11111111** [derrian-distro/LoRA_Easy_Training_Scripts#104]
Hi. I'm on a Linux Mint machine, and I'm getting an error. I can install the program and set everything up fine, but I get an issue when running the run.sh file:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, eglfs, linuxfb, vnc, vkkhrdisplay, wayland-egl, offscreen, minimalegl, xcb, wayland.

./run.sh: line 2: 959268 Aborted                 (core dumped) python main.py
There are a large number of different posts about this same error on different forums, and it seems to be either the result of an error of PyQt6 or some python module which depends on it. I have tried many of the fixes proposed, but none of them have worked. 
    1) I have installed, uninstalled, and reinstalled PyQt5, PyQt6, libxcb-icccm4, libxcb-image0, libxcb-keysyms1, and libxcb-render-util0 from apt
    2) I have set the DISPLAY environment variable as 0 and as 1.
    3) I have installed, uninstalled, reinstalled, and installed different versions of opencv-python from pip
    4) I have located my libqxcb.so file (found at /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms), and run ldd on it, which produced no error messages, and it looked like everything was correctly linked
    5) I have set QT_QPA_PLATFORM=offscreen, which does successfully avoid crashing the program, but then of course the GUI isn't onscreen, so it isn't particularly useful. I have tried setting it to "wayland", but it gave the same error, except replacing the "xcb" with "wayland".
    6) I have a friend who runs Manjaro, and he was able to get the GUI running just fine

Any help would be appreciated :)

**Comment by derrian-distro** [comment]
I'm going to be 100% honest. I have no clue how to solve this issue. I don't use linux mint, not have tested my scripts on it. I'll leave this issue open for a time though in the hopes that somebody else has solved the issue and can share insight.

**Comment by lIlIlI11111111** [comment]
After a while of looking, I found the solution. I think Linux Mint does not come packed with all the libraries that Qt expects it to have. I installed the Qt dependencies of Libxcb according to the official Qt documentation, as found here, and it worked: https://wiki.qt.io/Building_Qt_5_from_Git.
In particular, I just had to run this line: `apt-get install libx11-xcb-dev libxcb-composite0-dev libxcb-cursor-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-present-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xtest0-dev libxcb1-dev`

**Comment by derrian-distro** [comment]
Great! I'm glad you figured it out. Linux support is hard to work with because of how different they all are. I'll leave this issue open so it's more visible to people

**Comment by Blucknote** [comment]
@lIlIlI11111111 thanks this helps

**Comment by Jelosus2** [comment]
I personally tested this and seems to be fixed so I'm closing this issue.
