### ISSUE TITLE
Issue with mixed flip enhance datasets 

### ISSUE THREAD

**Issue by knzro** [derrian-distro/LoRA_Easy_Training_Scripts#105]
This might be a Kohya's issue but it is best to at least get it documented here.
I am randomly receiving an error in train_network.py line 627. When using multiple folders with only some of them having flip enhance enabled.

`latents = vae.encode(batch["images"].to(dtype=weight_dtype)).latent_dist.sample()`

The issue immediately goes away when i enable or disable flip in all folders.

**Comment by LegionInstaller** [comment]
Same when having one of the subsets set to Flip it won't work

**Comment by derrian-distro** [comment]
yeah, that's an issue related to kohya, from the documentation it should work.
