### ISSUE TITLE
multi_GPU_lora_train

### ISSUE THREAD

**Issue by pengpengzi** [derrian-distro/LoRA_Easy_Training_Scripts#110]
Hello, can you tell me which configuration file I need to modify in order to train a LoRa model using two GPUs together? I'm experiencing an out-of-memory error when using one GPU, so I would like to utilize the memory of two GPUs.

**Comment by derrian-distro** [comment]
you need to run the accelerate config, and change the gpu to all, then modify the run,bat file to launch the main.py using `accelerate launch`

**Comment by pengpengzi** [comment]
> you need to run the accelerate config, and change the gpu to all, then modify the run,bat file to launch the main.py using `accelerate launch`

I followed your method and changed accelerate-launch in run.bat to open main.py. Then I got an error, and the error message said there was a conflict.
![图片](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/103752028/a6023645-3ea4-4953-8e0d-7be6a5816fbe)
