### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by tetsuoo-online** [derrian-distro/LoRA_Easy_Training_Scripts#111]
X:\Stable Diffusion\LoRA_Easy_Training_Scripts>install.bat
Traceback (most recent call last):
  File "X:\Stable Diffusion\LoRA_Easy_Training_Scripts\installer\installer.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

I don't know what to say, I have Python 3.10.11 installed, most others scripts works fine : auto1111,Vlad,ComfyUI, Kohya_ss... but there is always something to fix, right x)

**Comment by Jelosus2** [comment]
I'm not an expert in python and i didn't have this issue but have you tried to install pkg_resources with `pip install pkg_resource` or something like that?

**Comment by slimybastard** [comment]
I had to run 
`pip install requests`
and that fixed it on my end.

**Comment by derrian-distro** [comment]
oh? interesting, my installer installs requests if it's not installed hmm, I'll look into that

**Comment by nexoboii** [comment]
Similar error, tried to use the latest installer (v6) and got the error.
Traceback (most recent call last):
  File "C:\Ai_stuff\lora training\installer.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
not sure what to do about it

**Comment by nexoboii** [comment]
All i know is that with the pkg_resources is considered depreciated

**Comment by derrian-distro** [comment]
> Similar error, tried to use the latest installer (v6) and got the error. Traceback (most recent call last): File "C:\Ai_stuff\lora training\installer.py", line 5, in import pkg_resources ModuleNotFoundError: No module named 'pkg_resources' not sure what to do about it

all of the installers in the releases are considered deprecated, the install instructions state that you should clone the project then run the install.bat from within the folder.

as far as I know, pkg_resources wasn't deprecated in 3.10, which is the python version the scripts target. I'll look into it but on the only version I test on, 3.10.6 it seems to work fine
