### ISSUE TITLE
Training with two GPUs (GPU_ids=0,1) encountered an error: fp16 requires a GPU

### ISSUE THREAD

**Issue by pengpengzi** [derrian-distro/LoRA_Easy_Training_Scripts#114]
![图片](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/103752028/6b4f2e9d-bd21-476d-9426-3c145b2cef76)
like this，how can i solve it

**Comment by derrian-distro** [comment]
Make sure you are running with accelerate launch instead of just python, beyond that I can't really help as I don't have two gpus to test with

**Comment by UBBK** [comment]
what is an accelerate launch.i have an onboard gpu and i get memory error when i try to train. assuming its using onboard gpu
