### ISSUE TITLE
All of my own trained loras just output black

### ISSUE THREAD

**Issue by Accy587** [derrian-distro/LoRA_Easy_Training_Scripts#116]
Any other lora works just fine just not the ones that i train. My training images are all 512 x 512 like i have in the settings. I have even tried your recommended settings from https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/issues/85 too with the same outcome. I have used both stable-diffusion-v1-5 and stable-diffusion-2-1-base as my basses with the same outcome. I am running it on a new 3060 12gb so i know that it is not a gpu related issue. The sample images that it gives me are fine just not the output in stable diffusion they are all black. Any help would be greatly appreciated.

**Comment by derrian-distro** [comment]
The only thing I can see it being is Nan issues. Effectively, it's learning too much and bricking the lora. I don't know what you are training, but the template there is more or less for anime moreso than realism. If you see that loss goes to Nan during training, just kill it st that point, its already fried.

Beyond that, I couldn't tell you. If it works fine in previews all the way out, then it's very likely not a Nan issue, but rather an issue with kohya that I have not identified

**Comment by Accy587** [comment]
what steps would i take to fix it then?

**Comment by derrian-distro** [comment]
yeah, it's exactly that.
