### ISSUE TITLE
Add support for SDXL

### ISSUE THREAD

**Issue by watzon** [derrian-distro/LoRA_Easy_Training_Scripts#117]
kohya_ss supports SDXL now, it would be nice if this did too since this actually seems to run on my Linux system and kohya_ss has issues

**Comment by derrian-distro** [comment]
https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/tree/SDXL

I don't plan on merging it into main until sd-scripts does

**Comment by watzon** [comment]
Look at you go! I should've looked at the branches

**Comment by derrian-distro** [comment]
Note the sd-scripts and LyCORIS are slightly out of date right this moment.

Defaults are also not the best options for SDXL, I plan on updating this weekend.

At the very least, make sure you are training in bf16 precision.

**Comment by St33lMouse** [comment]
A few questions for SDXL training:
1) Do we need to click any buttons or do anything special to make it for SDXL?
2) Do images need to be square, or can we just dump them in the hopper?
3) What's the recommended size of SDXL images? 1024 x 1024? Can they be bigger?

**Comment by St33lMouse** [comment]
> > 
> 
> this is what SDXL was trained on (snippet from paper) https://preview.redd.it/69sfn578hseb1.jpeg?width=1439&format=pjpg&auto=webp&s=277f9d8bbeac72c8df55e29c956c3f6e1cd6ad37
> 
> Images can be any size, but you should try to not have smaller images if possible. Images above that size will be fit to the buckets (downscaled/cropped). Buckets mean you do not need square images. There's a tickbox for SDXL.

OK! and square doesn't matter?

**Comment by vin901** [comment]
@derrian-distro I don't see the SDXL branch any more? I assume its all in the branch named 'dev' is that correct? Thanks in advance, i prefer your gui/scripts over KohyaSS, keep up the good work!

**Comment by derrian-distro** [comment]
Sdxl has been merged into main, you can swap back to the main branch!

**Comment by vin901** [comment]
@derrian-distro That's awesome! Thanks for answering 🥇 :-)

**Comment by vin901** [comment]
@derrian-distro I apologize if this is a noob question, I've done quite a few SD1.5 LORAs so I tried training with SDXL using the base SDXL1.0 model and 10 images that are 1024x1024, using some recommended SDXL settings (based on KohyaSS actually), but I keep getting this error (below), not sure if I'm missing something or doing something wrong?

I have a 16gb 4060ti, and closed everything else just to make sure it wasn't OOM related.

I also tried turn on/off Buckets, Xformers, Cache Latents, SD2.X Based (which I assume should be unticked but tried it both ways anyways), but still the same error? Any ideas would be greatly appreciated, thanks!

```
 size mismatch for mid_block.attentions.0.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
Failed to train because of error:
Command '['I:\\AI-TRAINING\\LoRA_Easy_Training_Scripts-SDXL\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```

**Comment by derrian-distro** [comment]
odd error, I don't know the solution, I'd have to look into it. I haven't trained SDXL for a very long time, so I don't really know if anything drastically changed.

**Comment by vin901** [comment]
No worries, thanks.

**Comment by Jelosus2** [comment]
Closing this issue as SDXL support has already been implemented.
