### ISSUE TITLE
headless mode

### ISSUE THREAD

**Issue by moonshinegloss** [derrian-distro/LoRA_Easy_Training_Scripts#118]
it would be nice for those of us who run sdxl (or others) in cloud rented GPUs to generate a config (via GUI on another computer) or command we can run (similar to bmaltais "print command" button) to then run it headlessly with no gui in the cloud environment

**Comment by derrian-distro** [comment]
I'm working on this right now, I'll have a way to generate the tomls used during actual training in the next update, and hopefully a collab that can be used in conjunction, once I spend the time to work on a colab.
