### ISSUE TITLE
Save/Load dialogs don't appear if last location has been deleted

### ISSUE THREAD

**Issue by tofof** [derrian-distro/LoRA_Easy_Training_Scripts#119]
# Description
Save/load dialogs don't appear if the remembered directory location no longer exists.

# Steps to Reproduce
1. Save a toml file
2. Delete the directory containing that toml
3. Try either 'save toml' or 'load toml' and the file chooser UI does not appear.

# Expected behavior
The file chooser UI opens to the current working directory or some other sane location when it cannot access the last used directory.

# Technical
Windows 10
Commit [a85685b](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/commit/a85685b1c911f7993c573d8934ccfab4b9f1b058)

**Comment by derrian-distro** [comment]
on the SDXL branch, I have fixed this issue.
