### ISSUE TITLE
[SDXL Branch] UI behavior buggy on queue and start, can't run training

### ISSUE THREAD

**Issue by JenXIII** [derrian-distro/LoRA_Easy_Training_Scripts#120]
Reproduced on new SDXL branch, latest commit (cc964159b543230642f5fe5aa75d7c84b3e79109) set up from scratch just to make sure nothing borked in the update process in my old local repo.

When adding a training to queue it pops up a save dialogue for a toml file which is unexpected from old behavior patterns.  When starting any training (queued or from current config) it pops up a load dialogue for a toml and enters some sort of freeze or loop (also unexpected).  The following messages appear in terminal:

> runtime_store\1690714394372004400.toml
> QObject::startTimer: Timers can only be used with threads started with QThread

I can't train atm using the UI :(

**Comment by derrian-distro** [comment]
just pushed and update that should have fixed that issue.

**Comment by imuntyan** [comment]
Cloned and checked out the commit 6582bed, installed from scratch on windows. When the option 'Save Toml File' is checked then the behaviour is the same as described by @JenXIII: the UI pops up a save dialog, prints `QObject::startTimer: Timers can only be used with threads started with QThread` message and hangs. When it is not checked, it proceeds to training and fails with the following message:
```
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<?, ?it/s]
caching latents...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:09<00:00,  2.30it/s]
Traceback (most recent call last):
  File "J:\sd\projects\lets\sdxl\LoRA_Easy_Training_Scripts\sd_scripts\sdxl_train_network.py", line 174, in <module>
    trainer.train(args)
  File "J:\sd\projects\lets\sdxl\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 277, in train
    network = network_module.create_network(
  File "J:\sd\projects\lets\sdxl\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\lycoris\kohya\__init__.py", line 50, in create_network
    if preset not in PRESET:
TypeError: unhashable type: 'dict'
Failed to train because of error:
Command '['J:\\sd\\projects\\lets\\sdxl\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\sdxl_train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```

**Comment by derrian-distro** [comment]
ah, lycoris introduced a preset system recently. seems to be possibly broken. I'll look into fixing the other bug though

**Comment by derrian-distro** [comment]
alright, update pushed, should fix the same toml issue. also updated LyCORIS which should fix the other issue.
