### ISSUE TITLE
[feature] Drag folder with images or add all subfolders from folder

### ISSUE THREAD

**Issue by Darkenlord1** [derrian-distro/LoRA_Easy_Training_Scripts#121]
Would be good if i will be able to just drag folder with images right into window with subsets, hope it is possible in python  ui.
Or add all subfolders with subfolders in them through "add all subfolders from folder", in other words - recursively.

**Comment by derrian-distro** [comment]
I have implemented a button that you can use to select a folder, and it will add all folders the immediate level within it into the subsets. I believe this change has made it's way to main, but if not, it's most definitely in SDXL branch, which is serving as my dev branch for right now.
