### ISSUE TITLE
[feature] Throwing errors when there is no directory present for saving output

### ISSUE THREAD

**Issue by Darkenlord1** [derrian-distro/LoRA_Easy_Training_Scripts#123]
Instead of throwing error, why not keep it lighting red in ui and at start of training just create the folder?

**Comment by derrian-distro** [comment]
shouldn't be too hard to implement that, I just didn't want it to create a folder in a place the user didn't actually want, so I'm not 100% on making this change. I might make the change once I create a proper settings page.
