### ISSUE TITLE
linux venv run.sh No module named 'PySide6

### ISSUE THREAD

**Issue by frankchieng** [derrian-distro/LoRA_Easy_Training_Scripts#124]
i have reinstall pyside6 as following :python3.10 -m pip install --force-reinstall --no-cache-dir pyside6
then bash 'run.sh' ModuleNotFoundError: No module named 'PySide6'
![1690787981214](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/130369523/0b4122fd-c857-4805-9510-a89dccbdc553)

**Comment by derrian-distro** [comment]
My scripts don't work on colab. They are solely for use locally.

**Comment by LogixTheDev** [comment]
I'm having the same issue. Running ./run.sh in a local terminal produces this exact same error.

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/137100808/6d7e61c6-0d53-4df8-9e64-5e06153335f9)

**Comment by derrian-distro** [comment]
did you follow the install instructions before running run.sh?

**Comment by davejhahn** [comment]
@derrian-distro I am having the same problem "ModuleNotFoundError: No module named "PySide6".  

I saw your comment about following the install instructions, but the only instructions before running run.sh are:

- You need Python 3.10 (I have Python 3.10.12)
- And: 
```
sh -c "$(wget https://raw.githubusercontent.com/derrian-distro/LoRA_Easy_Training_Scripts/main/install.sh -O -)"
```
When it finishes running the above install, I don't see any errors except at the end:

```
accelerate configuration saved at /home/xxxx/.cache/huggingface/accelerate/default_config.yaml                                                                                
./run.sh: 1: source: not found                                                                                                                                                 
./run.sh: 2: python: not found  
```
It looks like PySide6 is installed:
```
pip3 install PySide6
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PySide6 in /home/xxxx/.local/lib/python3.10/site-packages (6.5.0)
Requirement already satisfied: PySide6-Addons==6.5.0 in /home/xxxx/.local/lib/python3.10/site-packages (from PySide6) (6.5.0)
Requirement already satisfied: shiboken6==6.5.0 in /home/xxxx/.local/lib/python3.10/site-packages (from PySide6) (6.5.0)
Requirement already satisfied: PySide6-Essentials==6.5.0 in /home/xxxx/.local/lib/python3.10/site-packages (from PySide6) (6.5.0)

```

**Comment by davejhahn** [comment]
I was able to get it to work.  The online script install does not seem to work, at least for me.  I ran through the manual install and got past that issue, then had another issue with "Could not load the Qt platform plugin "xcb".   I followed what was posted in https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/issues/104#issuecomment-1648909955 and got it running.

Thanks for listening :)  Adding this here for anyone else that might run into what I did.

**Comment by derrian-distro** [comment]
> I was able to get it to work.  The one line script install does not seem to work, at least for me.  I ran through the manual install and got past that issue, then had another issue with "Could not load the Qt platform plugin "xcb".   I followed what was posted in https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/issues/104#issuecomment-1648909955 and got it running.
> 
> Thanks for listening :)  Adding this here for anyone else that might run into what I did.
> 

Hmm, I'll have to look into that, I don't actually run Linux myself, but have a few friends that do test the scripts for me, I may have foo-bar'd something while I was updating things earlier and just didn't notice!
