### ISSUE TITLE
GPU Required

### ISSUE THREAD

**Issue by lordkitsuna** [derrian-distro/LoRA_Easy_Training_Scripts#125]
Hi, i just installed this and i followed the install instructions on the main page, they completed without error and the gui loads fine but when attempting to train i get 

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 980.23it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）bucket 0: resolution (384, 640), count: 1
bucket 1: resolution (448, 576), count: 4
bucket 2: resolution (512, 512), count: 2
bucket 3: resolution (640, 384), count: 2
mean ar error (without repeats): 0.06872373216549456
preparing accelerator
Traceback (most recent call last):
  File "/home/kitsuna/Pictures/Ai Images/git/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 873, in <module>
    train(args)
  File "/home/kitsuna/Pictures/Ai Images/git/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 161, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "/home/kitsuna/Pictures/Ai Images/git/LoRA_Easy_Training_Scripts/sd_scripts/library/train_util.py", line 3068, in prepare_accelerator
    accelerator = Accelerator(
  File "/home/kitsuna/Pictures/Ai Images/git/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Failed to train because of error:
Command '['/home/kitsuna/Pictures/Ai Images/git/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python', 'sd_scripts/train_network.py', '--config_file=runtime_store/config.toml', '--dataset_config=runtime_store/dataset.toml']' returned non-zero exit status 1.

i am probably missing something simple but i cant seem to figure out why it wont run

**Comment by derrian-distro** [comment]
hmm. i'm not entirely sure. that is a kohya issue vs an issue with my code, so I think opening up an issue over there would help in resolving it

**Comment by lordkitsuna** [comment]
understood thanks
