### ISSUE TITLE
Need some clarity on Instance Prompts and Class Prompts when using the GUI

### ISSUE THREAD

**Issue by TFWol** [derrian-distro/LoRA_Easy_Training_Scripts#126]
Could I get some more clarity on your approach to **Instance** and **Class** prompts?
I really like the GUI, but it's hard to approach when there's so many tutorials that mention these, so I'm unable to correlate with the repo.

The closest I could find to the possible approach you're using is from [here](https://github.com/darkstorm2150/sd-scripts/blob/c27974e0b292427d5e9a4f80d16e0200341b0777/docs/train_README-en.md?plain=1#L36)? 
Like a caption of `Character B in white clothes`

I would appreciate a quick example showing:
- what would be typed in the GUI (only need the sections dealing with structuring prompts) 
- what would be typed in a caption .txt file
  - that would assume:
      - class: dog
        `Character B dog in white clothes`?
          - can the character name have spaces? Is it best to use a rare token instead?
- the resulting prompt you would type in Automatic1111's WebUI to properly generate the images
  `a picture of <lora:Character B:1> dog in red clothes`?

**Comment by derrian-distro** [comment]
I don't use instance or class prompts in my UI. you can put an "activation" token at the front of the txt files you pass into the UI. but I do not provide to kohya any instance or class tokens.

**Comment by TFWol** [comment]
Understood, thanks!
