### ISSUE TITLE
[Bug] Comment field `'` breaks .toml file

### ISSUE THREAD

**Issue by TFWol** [derrian-distro/LoRA_Easy_Training_Scripts#127]
Using a `'` as in **you're** in the comments field breaks the .toml with unbalanced quote error once you start training.

**Comment by derrian-distro** [comment]
guess I have to do some pre-processing stuff to fix that, I'll fix it when I can

**Comment by derrian-distro** [comment]
i've looked into this bug and it seems to be related to the toml library itself so I can't change the library, but I might be able to escape it in post process? I still don't have a ton of time to work on the UI though, so I've been unfortunately unable to look into it further

**Comment by Charlweed** [comment]
I was blocked by this issue when I entered "I'm", but I was saved by this bug report. I was all ready to spend the day swimming through the python code.
Perhaps scan the comment field (perhaps all text fields?) as it it being entered, and refuse to accept text that would break the toml file?

**Comment by derrian-distro** [comment]
Yeah, from what I've gathered, it's the toml library, I *might* be able to still allow those characters by adding escape characters but I don't know if it will accept that if not then I'll just blacklist the characters

**Comment by TFWol** [comment]
I think the issue might be when the settings is put in `runtime_store\config.toml` since I can load the original .toml fine and it automatically corrects for the quote character.

```python
import toml

def main():
    with open('C:\\Stable Diffusion\\_Output\\auto_save_test.toml', 'r') as f:
        data = toml.load(f)
        print(data)

if __name__ == "__main__":
    main()
```
It outputs the contents of the .toml file.
Partial output:
```shell
{'subsets': [{'num_repeats': 1, 'keep_tokens': 2, 'caption_extension': '.txt', 'shuffle_caption': False,
...
etc.
... 
'max_train_steps': 1500, 'training_comment': "test isn't"}
```
The `'training_comment': "test isn't"` section gets surrounded by double quotes automatically.

I also tried a comment without the quote character and got `'training_comment': 'test blah'}`, where it ended up with single quotes.

When I modified `LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py` with:
```python
    print(f"Loading settings from {config_path}...")
    with open(config_path, "r") as f:
        print("config path")
        print(config_path)
        print("file")
        file_content = f.read()
        print(file_content)   # <==== Problem inside file
        f.seek(0)  # rewind the file
        config_dict = toml.load(f)
        print("config dict")
        print(config_dict)
```
I noticed the double quotes were converted back into single quotes:

```toml
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
max_train_steps = 1500
training_comment = 'blah'blah'
network_dim = 128
network_alpha = 128.0

```

I understand what the issue is, just don't know enough to fix it. Probably easy.

**Comment by TFWol** [comment]
I _finally_ found the issue. The same thing could probably be done for `create_dataset_args_file`, but I didn't want to touch what isn't broke.

**Comment by derrian-distro** [comment]
Thanks for looking into it, I haven't had the time. I'll pull it in once I am home from work

**Comment by derrian-distro** [comment]
I pulled this into dev, so I'll close this once I push it back to main
