### ISSUE TITLE
ImportError: libxkbcommon.so.0

### ISSUE THREAD

**Issue by kuso2006** [derrian-distro/LoRA_Easy_Training_Scripts#128]
After command"accelerate launch main.py --load_json_path <path>", get
<img width="877" alt="截屏2023-08-03 10 02 12" src="https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/109347845/1ffd3ea5-0f3a-4486-94ad-0f1240112f86">

**Comment by derrian-distro** [comment]
load_json_path is from a very old version. are you sure you installed the newest version?

**Comment by kuso2006** [comment]
yeah, It's a little old and I run the scripts in unbuntu server, which UI-related dynamic libs don't exist...

**Comment by derrian-distro** [comment]
Yeah, I can't help you then. They weren't ever intended to run on a server.
