### ISSUE TITLE
Add .none-use-foldername to the caption type selection

### ISSUE THREAD

**Issue by Signorlimone** [derrian-distro/LoRA_Easy_Training_Scripts#129]
As per title, I want to train using IA3 and, from what I've seen so far, you shouldn't use any caption for it. Fact is, there's no  way (at least that I know) to set the caption to be based on folder name. Is this an already present feature? If not, will it be implemented in the future?

**Comment by derrian-distro** [comment]
Just don't include .txt files in the image folder. That being said. I wouldn't believe the guide on that. Their results are far from satisfactory. They are just blowing hot air.

**Comment by Signorlimone** [comment]
@derrian-distro thanks for the answer, I'll keep that in mind!
