### ISSUE TITLE
Just wanted to know if v2 option was turned on by default and Clip skip=1 in the previous version.

### ISSUE THREAD

**Issue by SatyamSSJ10** [derrian-distro/LoRA_Easy_Training_Scripts#13]
Just wanted to know if v2 option was turned on by default and the Clip Skip was set to 2 in the previous version. I have trained 2 models with the latest version today, and the models are messed up. Like the problems in face and mouth. In the previous version I didn't had to deal with v2. The new options keep piling up and it is all getting complicated to maintain settings.
the commit : e981b54.
turning the option on is downgrading the products.

And can you add an option for Simple GUI, like Field = Value one, for the settings and options to set default values so wont have to choose configs file again or pick certain field from config and change what we want.

**Comment by derrian-distro** [comment]
V2 is not enabled by default in any version,
Clip skip is by default set to 2 in all versions

The reason why more and more popups appear is because more and more options appear, I plan on doing a complete ui eventually which will help alleviate this issue.

**Comment by SatyamSSJ10** [comment]
Thanks
