### ISSUE TITLE
SDXL Training gives an error

### ISSUE THREAD

**Issue by Signorlimone** [derrian-distro/LoRA_Easy_Training_Scripts#130]
Hi, I've switched to the SDXL branch to try and see if I can train a good LoRa for it but it keeps me giving this error after caching TE

Traceback (most recent call last):
  File "C:\AI\LoRA_Easy_Training_Scripts\sd_scripts\sdxl_train_network.py", line 174, in <module>
    trainer.train(args)
  File "C:\AI\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 325, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\AI\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3264, in get_optimizer
    if type(trainable_params) == list and type(trainable_params[0]) == dict:
IndexError: list index out of range
Failed to train because of error:
Command '['C:\\AI\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\sdxl_train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

this is my .TOML:

[[subsets]]
num_repeats = 1
keep_tokens = 0
caption_extension = ".txt"
shuffle_caption = false
flip_aug = false
is_reg = false
image_dir = "C:/Users/RINO/Pictures/LoRa_Training/MODERN ILLUSTRATION/images\\1_MODILL"

[noise_args]

[general_args.args]
pretrained_model_name_or_path = "C:/AI/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors"
mixed_precision = "fp16"
seed = 23
xformers = true
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
sdxl = true
no_half_vae = true
max_train_epochs = 10
cache_latents = true

[general_args.dataset_args]
resolution = 512
batch_size = 1

[network_args.args]
network_dim = 32
network_alpha = 32.0
cache_text_encoder_outputs = true
network_train_unet_only = true
min_timestep = 0

[optimizer_args.args]
optimizer_type = "Prodigy"
lr_scheduler = "constant"
learning_rate = 1.0
min_snr_gamma = 2

[saving_args.args]
output_dir = "C:/Users/RINO/Pictures/LoRa_Training/MODERN ILLUSTRATION/MODILLXL"
save_precision = "fp16"
save_model_as = "safetensors"
output_name = "MODILLXL_EASY_ROUND1_"
save_state = true

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[sample_args.args]
sample_prompts = "C:/Users/RINO/Pictures/LoRa_Training/prompt.txt"
sample_sampler = "ddim"
sample_every_n_steps = 1000

[logging_args.args]
logging_dir = "C:/Users/RINO/Pictures/LoRa_Training/MODERN ILLUSTRATION/MODILLXL/LOGS"
log_with = "tensorboard"
log_prefix = "MODILLXL_"
log_tracker_name = "MODILLXL_"

[network_args.args.network_args]
down_lr_weight = [ "1.0", "0.99", "0.96", "0.91", "0.84", "0.76", "0.65", "0.54", "0.42", "0.28", "0.14", "0.0",]
mid_lr_weight = 1.0
up_lr_weight = [ "1.0", "0.91", "0.82", "0.73", "0.64", "0.55", "0.45", "0.36", "0.27", "0.18", "0.09", "0.0",]

[optimizer_args.args.optimizer_args]
weight_decay = "0.000"
betas = "0.9,0.99"
eps = "1e-7"
d_coef = "8"
safeguard_warmup = "False"
use_bias_correction = "True"

-----------------------------------------------------------------------------------------------------------

If someone can help me I will be grateful

**Comment by derrian-distro** [comment]
The block weight stuff haven't been updated to work with SDXL I believe. So you will have to wait for kohya to get it working.

**Comment by Signorlimone** [comment]
@derrian-distro To be honest I tried also without and gave me the same error. I'll try to reinstall from scratch and see how it goes. Thanks for the answer nonetheless!

**Comment by derrian-distro** [comment]
I wonder if it's a prodigy issue then... hmm.

**Comment by Signorlimone** [comment]
@derrian-distro I don't think so, since I trained a ia3 with prodigy on SD1.5 without problems. I think it's something on my side, another problem I have is that no matter what I use in term of optimizer/lora type/settings my loss doesn't go down. It stays almost flat for the whole training. I'll test a bit and let you know if you are interested
