### ISSUE TITLE
Prodigy defaults

### ISSUE THREAD

**Issue by knzro** [derrian-distro/LoRA_Easy_Training_Scripts#132]
Could you add these defaults for the Prodigy Optimizer? I started doing some test with prodigy and the results has been stupidly better than my crappily finetuned AdamW for roughly 15% extra training time. These are the settings I used and seem to be the current consensus for LORA and LOCON.

[optimizer_args.args]
optimizer_type = "Prodigy"
lr_scheduler = "cosine"
learning_rate = 1.0
lr_scheduler_type = "LoraEasyCustomOptimizer.CustomOptimizers.CosineAnnealingWarmupRestarts"
lr_scheduler_num_cycles = 1
min_snr_gamma = 5

[optimizer_args.args.lr_scheduler_args]
min_lr = 1e-6
gamma = 0.9

[optimizer_args.args.optimizer_args]
weight_decay = "0.01"
decouple = "True"
use_bias_correction = "True"
safeguard_warmup = "True"
d_coef = "2"

**Comment by derrian-distro** [comment]
I won't be putting any defaults for prodigy. You can add them yourself using the optional args. That's the point of having them.

**Comment by derrian-distro** [comment]
I am gonna be honest though, I haven't found prodigy to be better than just using adamw8bit. To each their own, of course, but I just haven't seen any reason to use it myself.

**Comment by knzro** [comment]
> I am gonna be honest though, I haven't found prodigy to be better than just using adamw8bit. To each their own, of course, but I just haven't seen any reason to use it myself.

I agree with you on normal cases, it just seem to give me better concept separation when training extremely similar outfits and since i was training a concept that is so burnt in the original model it has become a black hole, it does a better job preventing overbaking than using Scaling weight normal. So you could give it a try when AdamW fails for those two reasons.
