### ISSUE TITLE
RuntimeError: Unrecognized CachingAllocator option: cudart

### ISSUE THREAD

**Issue by OzerSkyyy** [derrian-distro/LoRA_Easy_Training_Scripts#133]
That error pops up when I run a training and I don't understand how to fix it.

" File "E:\lora training\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: cudart "

**Comment by derrian-distro** [comment]
that's more of a sd-scripts issue, I suggest you open up an issue there.
