### ISSUE TITLE
How do we increase the Noise Offset field input width?

### ISSUE THREAD

**Issue by DarkAlchy** [derrian-distro/LoRA_Easy_Training_Scripts#134]
0.0357 WHile we can only input 0.0X, so ut needs two more places we can use.

**Comment by derrian-distro** [comment]
for SDXL, just don't input anything for noise offset, sd-scripts sets it for you.

**Comment by DarkAlchy** [comment]
Seriously?  I set my own and wish to use my own, and this part has always been the worst part people have complained about.  Besides, I really would like an answer to the question as to how we can do it and not just sweeping it under the rug.

**Comment by derrian-distro** [comment]
really? hmm, why has nobody come to me about it before now then? I might get around to it.

**Comment by Hosiokaa** [comment]
@DarkAlchy 
You should be able to override the UI elements by entering your own values in the TOML. However, the only reason you might want to tinker with the noise offset is if you want to use the pyramid noise offset instead of the normal noise offset.

**Comment by DarkAlchy** [comment]
> @DarkAlchy You should be able to override the UI elements by entering your own values in the TOML. However, the only reason you might want to tinker with the noise offset is if you want to use the pyramid noise offset instead of the normal noise offset.

Well, thank you, but I went to other sources because it really is a HUGE oversight not allowing use to be the masters of our own destiny.  In other words way more than two digits after the decimal point.  

Thank you again.
