### ISSUE TITLE
how to set reg_data_dir

### ISSUE THREAD

**Issue by Phrixus2023** [derrian-distro/LoRA_Easy_Training_Scripts#138]
i very like your training scripts.but i don't know how to set regdata, select "reg images" and i can't find where to set reg_data_dir

**Comment by derrian-distro** [comment]
in the subset menu, there is a checkbox to denote a specific subset is regularization images.

**Comment by Phrixus2023** [comment]
> 

is that mean two subset ? one is images  one is reg images,but reg images subset need select "regimages"

**Comment by derrian-distro** [comment]
Yes. This is because sd-scripts registers them as a subset as well. Don't ask me why they chose to do it this way, but it honestly was easiest to just make use of what was already there.

**Comment by Phrixus2023** [comment]
> Yes. This is because sd-scripts registers them as a subset as well. Don't ask me why they chose to do it this way, but it honestly was easiest to just make use of what was already there.

thanks very much~

**Comment by derrian-distro** [comment]
no problem!
