### ISSUE TITLE
Can the UI poll if the files in the runtime folder has changed?

### ISSUE THREAD

**Issue by nochekaiser** [derrian-distro/LoRA_Easy_Training_Scripts#139]
I love your work btw! but I am starting to feel annoyed with the one by one queueing so I tried digging a bit. I noticed that it saves the config files in the runtime folder for each item in the queue. Changing some values with the toml files will reflect on the UI, however, it doesn't see when a new toml file is added manually in the folder. Can the UI poll for changes in the runtime folder or rather... what is the script that should run to train the config files in the runtime folder?

**Comment by derrian-distro** [comment]
The queue system makes that a bit annoying, but I could probably get it to work, I'll look into it.
