### ISSUE TITLE
Resize Script

### ISSUE THREAD

**Issue by amarney4862** [derrian-distro/LoRA_Easy_Training_Scripts#141]
Forgive me if I've missed something, but it seems like the new UI (which is great) does not have an option to resize LoRAs. Was that simply removed, or was it moved somewhere?

**Comment by derrian-distro** [comment]
It isn't in the new ui for now. I haven't had enough time to add it back in, I do plan on adding it eventually, I'd like to add it back in sooner rather than later, but time is unfortunately not something I have a ton of anymore.

**Comment by Jelosus2** [comment]
Closing this as its been implemented already on dev branch and soon will be merged to main.
