### ISSUE TITLE
persist queue across restarts

### ISSUE THREAD

**Issue by moonshinegloss** [derrian-distro/LoRA_Easy_Training_Scripts#143]
currently runtime_store still has all the .toml from the previous run, but if you quit out or want to prematurely end and later continue, you'll be greeted by an empty queue, is there a way to just keep the previous queue on startup? (e.g. check if runtime_store still contains the toml files) thanks

**Comment by derrian-distro** [comment]
it should be possible, I'll look into adding it when I get some time to work on the UI. I've been pretty busy lately, so time to update has been sparse

**Comment by moonshinegloss** [comment]
@derrian-distro worth revisiting? queue_store seems to contain the files now, but on boot-up it's all empty, would be useful to e.g. put all files you want queued in there with a script and then simply open the GUI to start the queue processing, thanks
