### ISSUE TITLE
Issue with "Load Toml" option.

### ISSUE THREAD

**Issue by Jelosus2** [derrian-distro/LoRA_Easy_Training_Scripts#146]
At the beggining it worked as intended but since 3-4 days whenever i try to use the "Load Toml" option it closes the menu and doesn't even displays the file explorer to select the file. I've tried restarting the PC and the trainer but nothing changed. Do you have information about why this could have happened?

**Comment by derrian-distro** [comment]
It might be because of an invalid path listen in the config.json file for loading the toml, I have already fixed this bug on the sdxl branch, but haven't pushed it to main because I am waiting for kohya to merge their sdxl branch to main.

**Comment by Jelosus2** [comment]
So is there's anything i can do to solve it? Or I simply have to wait for it to be pushed to the main branch?

**Comment by derrian-distro** [comment]
You can just delete your config.json in the root of the folder. That should fix it, though it will undo your theme selection as well

**Comment by Jelosus2** [comment]
I see, thanks for the quick reply, hope to see more of your work!

**Comment by Jelosus2** [comment]
Great, it worked! Thanks
