### ISSUE TITLE
Linux - Popup.py TypeError

### ISSUE THREAD

**Issue by Anon3024** [derrian-distro/LoRA_Easy_Training_Scripts#15]
When attempting to run popup.py TypeError is thrown on line 897, in ButtonBox see output below:
`Traceback (most recent call last):
  File "lora_train_popup.py", line 896, in <module>
    class ButtonBox:
  File "lora_train_popup.py", line 897, in ButtonBox
    def __init__(self, label: str, button_name_list: list[str]) -> None:
TypeError: 'type' object is not subscriptable
`

Running in venv environment as per [Linux Lora Training Trouble shooting guide](https://rentry.org/lora-linux-troubleshooting), except attempting to run lora_train_popup.py instead of the command line version.

Have attempted to run both through accelerate launch (`accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.py`) and via a direct python call (`python3 lora_train_popup.py`)

**Comment by derrian-distro** [comment]
Hi, can I get a bit more detail about your environment? thinks like the version of python you have, the version of Linux you are on, and if you have tkinter installed

**Comment by Anon3024** [comment]
Sure thing!
Python 3.8.10
Linux Distro: Mint 20.3
tkinter 8.6 is installed.

**Comment by derrian-distro** [comment]
hmm, it might actually be because of your Python version, I wrote these scripts with the expectation that they will be on 3.10.6, the same version that SD-Scripts was built for. However, looking into your error, it might just be a case of the type hinting that I am using for it.

Can you remove the  `-> None` from the `__init__` function within my scripts?
so change line 897 to
    def __init__(self, label: str, button_name_list: list[str]):

**Comment by Anon3024** [comment]
Getting the same error, see output below:
`Traceback (most recent call last):
  File "lora_train_popup.py", line 896, in <module>
    class ButtonBox:
  File "lora_train_popup.py", line 897, in ButtonBox
    def __init__(self, label: str, button_name_list: list[str]):
TypeError: 'type' object is not subscriptable
`

**Comment by derrian-distro** [comment]
hmm, give me a bit to spin up a linux mint WSL instance so I can try and replicate this.
I feel like it's related to your version of python though.

**Comment by Anon3024** [comment]
I'll go ahead and update my python and try again too, please hold.

**Comment by Anon3024** [comment]
You were correct! Updating Python to 3.10.9 fixed it.

Thank you for helping me out with this!

**Comment by derrian-distro** [comment]
it's no problem, thanks for bringing it up, it will be useful to have to point to next time I get a bug report like this
