### ISSUE TITLE
Request - Prevent accidental value changes when scrolling through QT UI

### ISSUE THREAD

**Issue by TFWol** [derrian-distro/LoRA_Easy_Training_Scripts#151]
When scrolling down the UI via mouse wheel it's way too easy to change values by accident without realizing it.

I've borked quite a few projects from this; it's hard to notice what may have changed due to all of the various tweaks, settings and numbers involved.

Can something be added that will help mitigate this?

A couple of ideas:
- a quick 'read only' toggle 
- locks next to all fields so you can mark the ones you don't intend on changing.

**Comment by derrian-distro** [comment]
all of the scrollable elements have been locked until you click on them for months now, are you up to date?

**Comment by derrian-distro** [comment]
![python_XfIh1kcKlN](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/121591654/e11505b6-c423-4ec7-82a0-1846edc78526)

example to show that I mean

**Comment by derrian-distro** [comment]
no problem, glad I could help!
