### ISSUE TITLE
text encoder upstream bug

### ISSUE THREAD

**Issue by moonshinegloss** [derrian-distro/LoRA_Easy_Training_Scripts#154]
is LETS affected by this and if yes, will the fix be merged? https://github.com/kohya-ss/sd-scripts/issues/890 thanks

**Comment by derrian-distro** [comment]
I just use sd_scripts as the backend, so if it gets pushed to sd_scripts, then it will get pushed to this repo when it gets merged there, as I periodically update sd_scripts

**Comment by zethfoxster** [comment]
i wonder if its related to the reason im looking through bugs myself
let me show you....
![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/5951657/eee45ff9-dd4f-4068-a973-e769fded9dd2)
these are samples during training a coloring book lora...looks fantastic...
![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/5951657/4ff43190-cd34-4c46-9e4d-ab3dac5fe743)
same settings, seed, sampler, and prompt on same model it trained on. it wont produce a single line drawing like the sample produce.

**Comment by derrian-distro** [comment]
I uh... Yeah i'm not sure. I don't believe that is an issue I personally can fix unfortunately. It seems like a kohya issue.
