### ISSUE TITLE
Nonfunctional installation on Windows 10

### ISSUE THREAD

**Issue by Chudjak** [derrian-distro/LoRA_Easy_Training_Scripts#16]
Using install_sd_scripts_v4.bat gives 
![image](https://user-images.githubusercontent.com/122031986/220631407-4ad66556-83ac-40b5-96a6-703d3da809e6.png)
a lot of errors, and thus the run_popup.bat doesn't work due to accelerate not getting downloaded.
![cmd_81lygJUoy5](https://user-images.githubusercontent.com/122031986/220631506-b94f0656-4b1a-4b52-8437-dd2a54194958.png)
Note that pip should be at the latest version, I have no idea where the pip isn't updated error comes from.
![image](https://user-images.githubusercontent.com/122031986/220631631-1f4bfa0e-ac2c-41ba-b74c-38c85752b604.png)

**Comment by Chudjak** [comment]
I deleted all my python instances and installed 3.10 and now it works. I think adding that 3.10 is needed to the project's readme would be a good idea.

**Comment by derrian-distro** [comment]
Ah, my apologies, I didn't think to include thay because the assumption I had was that you already had python 3.10, because that's the version that webui, and sd-scripts itself expects. I'll make sure to add it to the instal instructions

**Comment by turnitoff92** [comment]
I have this problem using 3.10.9... I think the problem is with torch installation being incompatible with CUDA? webui uses `torchvision-0.14.1+cu117.dist-info` and sd-scripts uses `torchvision-0.13.1+cu116.dist-info`

**Comment by derrian-distro** [comment]
That's what sd-scripts requires, I can't exactly change that.

**Comment by 2blackbar** [comment]
yeh this is pretty bad, it installs torch without cuda, missing shitload of dependencies... what the hell man

**Comment by derrian-distro** [comment]
it does install torch with cuda, the command I use to install it is *exatly* the same one as on sd-scripts
`pip3 install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 > nul`
