### ISSUE TITLE
Expose Batch VAE option

### ISSUE THREAD

**Issue by lzardy** [derrian-distro/LoRA_Easy_Training_Scripts#162]
Basically the title. Current kohya_ss gui has a Batch VAE option with number of batches. This speeds up initial caching and mid-training usage of VAE.

**Comment by derrian-distro** [comment]
oh, sure, didn't realize it was an arg, can add that sometime this week, assuming I get time

**Comment by derrian-distro** [comment]
![image](https://github.com/user-attachments/assets/32ec85a9-6053-4e04-83b0-c60ab5c1f36b)
you can add the arg as an extra arg in the bottom section, keep in mind that I don't do any error handling on that section of inputs, so double check to make sure the input is the correct value!
