### ISSUE TITLE
Perform Additional Training on Existing LoRA

### ISSUE THREAD

**Issue by Kexus** [derrian-distro/LoRA_Easy_Training_Scripts#169]
Is it possible to perform additional training on an existing LoRA using the gui without using save/resume state? Kohya supports a --network_weight argument to specify a network to use as the base for training, but there doesn't appear to be any way to set this through the gui.

**Comment by derrian-distro** [comment]
the network_weight argument isn't for resuming training, all that does is set the block weights according to the current size of the lora, it won't help you in this scenario

**Comment by Kexus** [comment]
Maybe I'm reading it wrong, but this comment from Kohya says that --network_weight is used to continue training an existing model
https://github.com/kohya-ss/sd-scripts/issues/466#issuecomment-1537264519
This is also repeated here: https://github.com/bmaltais/kohya_ss/wiki/LoRA-training-parameters#lora-network-weights
"If you want to use the already learned LoRA file for additional learning, specify the LoRA file here."

**Comment by derrian-distro** [comment]
hmm, they must have changed their implementation then, as it very much used to not be for that

**Comment by Jelosus2** [comment]
> Missing this feature as well. Maybe just generally add a field for additional commandline-arguments, so people could use "--network_weight " or whatever options they want, that can not be set via GUI?
> 
> > hmm, they must have changed their implementation then, as it very much used to not be for that
> 
> Been using the feature for over a year, and AFAIK it was always for that.

A way to add options to the training that is supported by the sd scripts is editing the config.toml that is generated once you start training

**Comment by Jelosus2** [comment]
till point 3 is right. For step 4 you could use this workaround
```
# Windows
.\venv\Scripts\activate

# Linux (Give permission with chmod to the file first)
.\venv\bin\activate

# train_network.py for 1.5
python sdxl_train_network.py  --config_file=/path/to/config.toml --dataset_config=/path/to/dataset.toml
```

**Comment by neojam** [comment]
Thanks, I will try that.

**Comment by Jelosus2** [comment]
np, the venv is located on the sd_scripts directory tho

**Comment by MOGRAINEREPORTS** [comment]
It's closed on the other duplicated thread as complete but i can't figure out how to do it, can someone explain me please?

**Comment by Jelosus2** [comment]
It's not yet implement, the other issue was a duplicate so I closed it. As of now if you want to resume training you have to use the Save State option in Saving Args to save it and then use the Resume from State option to resume from the previous last saved state.

**Comment by derrian-distro** [comment]
to resume from lora weights, all you need to do is use the extra args section and put in network_weight and then the path to the lora in the other box. keep in mind I don't do any error checking at all on that section, so if it errors, it's likely because of an issue in the path

**Comment by derrian-distro** [comment]
![image](https://github.com/user-attachments/assets/2f293e5f-74b6-45d0-8e02-3ab2bced9350)
it should look something along the lines of this.

**Comment by MOGRAINEREPORTS** [comment]
> to resume from lora weights, all you need to do is use the extra args section and put in network_weight and then the path to the lora in the other box. keep in mind I don't do any error checking at all on that section, so if it errors, it's likely because of an issue in the path

do i do both?
Do i add the weight on top of resuming state?

**Comment by derrian-distro** [comment]
Make sure your file path is in linux format (/ instead of \\)
