### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by DarqueLilly** [derrian-distro/LoRA_Easy_Training_Scripts#170]
I cant train sdxl because of this error, can someone please help me or guide me in the right direction for training SDXL in Lora trainer

Traceback (most recent call last):
  File "Y:\Z-LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\sd_scripts\sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "Y:\Z-LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "Y:\Z-LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 1917, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "Y:\Z-LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 950, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "Y:\Z-LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 2260, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: Y:/LoraCreation/StyleLoras/Stylized-Art/TypographyAstrology\typographyart-01.png
Failed to train because of error:
Command '['Y:\\Z-LoRA_Easy_Training_Scripts\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\sdxl_train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by DarqueLilly** [comment]
![WindowsTerminal_UeMfETZ1UO](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/111714884/b4546927-a600-4cd9-9b53-a761e91a97dd)

**Comment by derrian-distro** [comment]
```
raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: Y:/LoraCreation/StyleLoras/Stylized-Art/TypographyAstrology\typographyart-01.png
```
this right here tells me it's an image that is causing it to break. This also means that the issue isn't on my end, but kohya's end. either delete this image, or edit it to try and prevent it from NaN-ing

**Comment by HolyCheems** [comment]
> ```
> raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
> RuntimeError: NaN detected in latents: Y:/LoraCreation/StyleLoras/Stylized-Art/TypographyAstrology\typographyart-01.png
> ```
> 
> this right here tells me it's an image that is causing it to break. This also means that the issue isn't on my end, but kohya's end. either delete this image, or edit it to try and prevent it from NaN-ing

I also experienced this issue earlier tonight - what do we do to images to keep them from NaN-ing?

**Comment by derrian-distro** [comment]
I don't know, as I've never had to deal with that. I can assume maybe putting it into paint and then saving it into a new file might work. this is only a suggestion though, as I really don't know the best way to solve it

**Comment by derrian-distro** [comment]
That is a toml loading error... like usual. For now, make sure you don't have any of `'`, `"`, `\`, and `,` in your paths. If you are on windows then you'll have to manually convert the \\ to / for now. I am currently in the middle of a rewrite, so hopefully these issues will be solved in the future.

**Comment by Woisek** [comment]
> That is a toml loading error... like usual. For now, make sure you don't have any of `'`, `"`, `\`, and `,` in your paths. If you are on windows then you'll have to manually convert the \ to / for now. I am currently in the middle of a rewrite, so hopefully these issues will be solved in the future.

But training with the same settings (slashes and stuff) and a SD 1.5 model works ... 😐

**Comment by DarqueLilly** [comment]
> manually convert the \ to / for now

So I understand The error, how to manually convert the \ to /? is there a way to do this?

**Comment by Woisek** [comment]
> So I understand The error, how to manually convert the \ to /? is there a way to do this?

Search and replace in the toml file ... ? 🤷‍♂️
