### ISSUE TITLE
[Solved it] UTF8/Japanese character issue -> after fresh install, failure to be runable. (common "Triton" error)

### ISSUE THREAD

**Issue by markusNirpaw** [derrian-distro/LoRA_Easy_Training_Scripts#172]
Trying to run a training after installing: 

$ ./run.bat
(gui setup)->(Launch training)

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading settings from runtime_store\config.toml...
runtime_store\config
prepare tokenizer
update token length: 225
Loading dataset config from runtime_store\dataset.toml
prepare images.
found directory D:/AICharacterTraining/Ryslee contains 583 image files
2332 train images with repeating.
0 reg images.
Traceback (most recent call last):
  File "D:\AICharacterTraining\LoRA_Easy_Training_scripts\sd_scripts\train_network.py", line 996, in <module>
    trainer.train(args)
  File "D:\AICharacterTraining\LoRA_Easy_Training_scripts\sd_scripts\train_network.py", line 198, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "D:\AICharacterTraining\LoRA_Easy_Training_scripts\sd_scripts\library\config_util.py", line 433, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "D:\AICharacterTraining\LoRA_Easy_Training_scripts\sd_scripts\library\train_util.py", line 1495, in __init__
    print("no regularization images / \u6b63\u5247\u5316\u753b\u50cf\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3067\u3057\u305f")
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 27-42: character maps to <undefined>

**Comment by markusNirpaw** [comment]
Looks like the toml error others are running into; Ive run through all permutations of fixing the slashes, still no joy. Toml file is as follows:

[[subsets]]
num_repeats = 4
caption_extension = ".txt"
shuffle_caption = true
flip_aug = false
color_aug = false
random_crop = false
is_reg = false
image_dir = "D:/AICharacterTraining/Ryslee"
keep_tokens = 1

[noise_args]

[sample_args]

[logging_args]

[general_args.args]
pretrained_model_name_or_path = "D:/AIStuff/EasyFluffV11_2.safetensors"
mixed_precision = "fp16"
seed = 23
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
clip_skip = 2
max_train_epochs = 5

[general_args.dataset_args]
resolution = 512
batch_size = 2

[network_args.args]
network_dim = 32
network_alpha = 16.0
min_timestep = 0
max_timestep = 1000

[optimizer_args.args]
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine"
learning_rate = 0.0005
max_grad_norm = 1.0
unet_lr = 0.0005
text_encoder_lr = 0.0005

[saving_args.args]
output_dir = "D:/AICharacterTraining/RysleeModelOutputs"
save_precision = "fp16"
save_model_as = "safetensors"
save_every_n_epochs = 1

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
betas = "0.9,0.99"

**Comment by markusNirpaw** [comment]
Adendum, this appears to be related to the chinese (?) characters in the python script;

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/5481742/b46f3cca-d650-4890-9598-db3f53405f97)

**Comment by markusNirpaw** [comment]
pip install win-unicode-console is what you want; this gives windows the ability to deal with the characters. (at least for me),

**Comment by derrian-distro** [comment]
That is an interesting issue, and one that I've never gotten. That is actually an issue with sd-scripts, the backend that I use, then. good to know for the future though, closing this issue for now.
