### ISSUE TITLE
Adafactor not working

### ISSUE THREAD

**Issue by smasonlawrence** [derrian-distro/LoRA_Easy_Training_Scripts#173]
I am getting an error when trying to train with Adafactor, can someone please clarify what is going wrong and how I can fix it? AdamW works fine, but I was told Adafactor works best for real people. I am using an RTX 3090 GPU.

Does it have something to do with the beta's argument? And if so are they relevant/necessary or redundant from my AdamW config?

Shell output below:

prepare optimizer, data loader etc.
use Adafactor optimizer | {'weight_decay': 0.1, 'betas': (0.9, 0.99), 'relative_step': True}
relative_step is true / relative_stepがtrueです
learning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されます
use adafactor_scheduler / スケジューラにadafactor_schedulerを使用します
Traceback (most recent call last):
  File "J:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 996, in <module>
    trainer.train(args)
  File "J:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "J:\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3676, in get_optimizer
    optimizer = optimizer_class(trainable_params, lr=lr, **optimizer_kwargs)
TypeError: Adafactor.__init__() got an unexpected keyword argument 'betas'
Failed to train because of error:
Command '['J:\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment]
yeah, adafactor doesn't support betas, just make sure to remove that arg in the second tab of the optimizer args. the defaults that I set are intended for adamw8bit as that is the one I personally suggest to use
