### ISSUE TITLE
Saving Epochs?

### ISSUE THREAD

**Issue by Woisek** [derrian-distro/LoRA_Easy_Training_Scripts#177]
I'm not quite sure, but how are epochs saved when I do, i.e., 10? What/Where is the option for that?
Thanks for this great tool.

**Comment by derrian-distro** [comment]
You will find the option in the saving args section. I believe it's called save frequency, you'll want to enable that and set a value, that will be how often it saves (in terms of epochs).

Note I might have the name wrong, I don't have access to my computer right this moment.

**Comment by Woisek** [comment]
Thanks, this was the option I was searching for. 👍
