### ISSUE TITLE
Subject: Inquiry about --fp8_base feature support in Easy Training Script

### ISSUE THREAD

**Issue by katyukuki** [derrian-distro/LoRA_Easy_Training_Scripts#179]
Dear 　[LoRA_Easy_Training_Scripts] Team,
I hope this message finds you well. I am reaching out to inquire about the --fp8_base feature within the Easy Training Script project. I have been attempting to utilize this feature but seem to encounter difficulties in getting it to work as expected. Before proceeding to ask for enhancements or modifications, I wanted to ensure that I am not missing any specific steps or configurations required for its implementation.

Could you kindly confirm if there are any particular instructions or prerequisites for using the --fp8_base feature within your project? If my approach is correct and the feature is currently not supported, would it be possible to consider its implementation in a future update? I believe this feature could significantly benefit users like myself for [briefly explain your use case, if applicable].

Here is what I have tried so far:

"I attempted to add fp8_base = true under the [optimizer_args.args.optimizer_args] section as per the instructions, but unfortunately, I encountered an error and was unable to execute the script successfully."

I apologize if this information is available and I missed it; I have checked the documentation and previous issues but could not find a clear answer.

Thank you very much for your time and assistance. Your project has been incredibly helpful, and I look forward to possibly contributing to it in the future.

Best regards,
katyukuki

**Comment by derrian-distro** [comment]
yes, it's not supported right this moment, I am in the process of a complete rewrite from the ground up, so it will be a bit longer before I update the UI again, but adding in fp8 support is planned with the rewrite. I'll close this issue once the rewrite is out.

just a heads up, this rewrite will change the the overall function of the backend, but will not change (massively) the frontend, despite doing a complete rewrite of both sections of the UI.

**Comment by katyukuki** [comment]
Thanks for the reply.
I am very much looking forward to the implementation!

**Comment by Jelosus2** [comment]
Closing this as fp8 has been implemented on dev branch and it will soon be merged into main branch.
