### ISSUE TITLE
Massively Higher VRAM Requirements on Windows

### ISSUE THREAD

**Issue by ripandtearr** [derrian-distro/LoRA_Easy_Training_Scripts#181]
Here on Windows, this new GUI version throws errors about missing packages like "Triton". Google says they are linux-only but optional.

Trying to train LORAs with the same settings as prior runs with this kit (at least I think they're the same?) causes me to instantly run out of VRAM on my 4090. Any way to install the older non-GUI version?

**Comment by ripandtearr** [comment]
Nevermind, just needed to enable SDPA/xformers

**Comment by derrian-distro** [comment]
Yes, I don't have it enabled by default as a "just in case". I have heard of a version of triton that works for windows, but I don't believe it was merged yet, so I'm not sure on including it quite yet
