### ISSUE TITLE
decouple savestate & lora output folder

### ISSUE THREAD

**Issue by blu3nh** [derrian-distro/LoRA_Easy_Training_Scripts#183]
Would it be possible to supply an optional different output folder for the savestate folder?

For context. When dealing with network shares, then saving the resulting lora to a remote server for instant testing works just fine, but savestate crashes the script due to the not fast enough transfer speed.

But even without that, I'm sure there's value in people saving directly to their monitored lora folder, even if local, without clogging it up with savestates.

**Comment by derrian-distro** [comment]
I don't believe that is an input in kohya, I'll double check

**Comment by derrian-distro** [comment]
yeah, it doesn't look like it is an argument within sd-scripts, so I won't be able to add it, unfortunately
