### ISSUE TITLE
xformers Update

### ISSUE THREAD

**Issue by ThesiiNCey** [derrian-distro/LoRA_Easy_Training_Scripts#187]
Would it be possible to add a more recent version of xformer?
Because with the old 0.14 there are more errors when training when it comes to things like fingers or toes

Because the memory optimization on the newer models is better configured when it comes to the memory blocks, more accurate results are achieved

**Comment by derrian-distro** [comment]
It's using the most recent version that is compatible on all systems, if you want to update it, I ask that you do it yourself.
