### ISSUE TITLE
loal TOML menu doesn't find any TOML

### ISSUE THREAD

**Issue by LoRAMilkshake** [derrian-distro/LoRA_Easy_Training_Scripts#188]
after I finished a LoRA training I clicked on File > Save TOML, the file was saved on my computer, but later when I needed to load it, it doesn't appear on the explorer window, nor I am unable to change the kind of files the windows show to me, the only option is "config files"

**Comment by derrian-distro** [comment]
yes, it should be `Config File (*.toml)` as the only option. are you sure you saved the toml file in the location you provided? I have never seen this issue *ever* so I can't provide any more help

**Comment by LoRAMilkshake** [comment]
> yes, it should be `Config File (*.toml)` as the only option. are you sure you saved the toml file in the location you provided? I have never seen this issue _ever_ so I can't provide any more help

yeah, I totally double and triple checked it was the same location. I'll try give the files the .toml extension, maybe that's the issue (I don't get why they aren't saved with it beforehand
)

**Comment by Jelosus2** [comment]
The config files should be saved with .toml extension huh

**Comment by Jelosus2** [comment]
Closing this because it should be fixed as of now or its a mistake from the user part
