### ISSUE TITLE
Error with lora_train_command_line.py

### ISSUE THREAD

**Issue by watermelon-juice-maker** [derrian-distro/LoRA_Easy_Training_Scripts#19]
Hello all,

I had been using this script for few days without problems but yesterday I encountered the following error message.

lora_train_command_line.py: error: ambiguous option: --lr_scheduler=cosine_with_restarts could match --lr_scheduler_num_cycles, --lr_scheduler_power

I have tried to set these arguments to none but it doesn't work. I am not sure what I need to change to fix the error.

You assistance is much appreciated!

**Comment by derrian-distro** [comment]
it was an error introduced in a recent update of sd-scripts, I should have an update out somewhat soon, which is a complete overhaul, which means it will require you to use the new installer I will also release with the update, but I am almost done with this big update, please give me a bit more time to work out the bugs and test

**Comment by watermelon-juice-maker** [comment]
> 

Excellent! Thank you so much for your effort!
