### ISSUE TITLE
I'd use this but lost and no where to find guidance.

### ISSUE THREAD

**Issue by DarkAlchy** [derrian-distro/LoRA_Easy_Training_Scripts#192]
Way too many settings, compared to kohya, that has no popup description on them so I have no idea what to set to what or if to even touch them.

Be nice to get a hold of some example toml files (as we have in kohya_ss gui) as a starting point to tweak, and a nice place for some documentation.

**Comment by TanvirHafiz** [comment]
yeah I feel lost too. Here can you add how many epochs you want to train? I only get no of images x repeats, but no no of trainng epochs!

**Comment by Jelosus2** [comment]
> Way too many settings, compared to kohya, that has no popup description on them so I have no idea what to set to what or if to even touch them.
> 
> Be nice to get a hold of some example toml files (as we have in kohya_ss gui) as a starting point to tweak, and a nice place for some documentation.

1. Kohya are the scripts used for training, the web UI is called bmaltais
2. There isn't much needed to change on this trainer compared to bmaltais's from my experience

**Comment by Jelosus2** [comment]
> yeah I feel lost too. Here can you add how many epochs you want to train? I only get no of images x repeats, but no no of trainng epochs!

You can set how many epochs you want to train in the "Max Training Time" option in the General Args. Also formula is `steps = (images * repeats * epochs) / batch size`

**Comment by DarkAlchy** [comment]
> > Way too many settings, compared to kohya, that has no popup description on them so I have no idea what to set to what or if to even touch them.
> > Be nice to get a hold of some example toml files (as we have in kohya_ss gui) as a starting point to tweak, and a nice place for some documentation.
> 
> 1. Kohya are the scripts used for training, the web UI is called bmaltais
> 2. There isn't much that needs to be changed on this trainer compared to bmaltais's from my experience

Kohya_ss gui as I mentioned vs Kohya sd-scripts or did you not see that?

Where is the documentation on this?  Where are the popups (one had one popup) for this?  Seriously, when answering do help as I asked for documentation on these not "There isn't much that needs to be changed" when I start it and most stuff is not checked and uses nomenclature I have not seen in Kohya_ss gui before.

**Comment by Jelosus2** [comment]
> > > Way too many settings, compared to kohya, that has no popup description on them so I have no idea what to set to what or if to even touch them.
> > > Be nice to get a hold of some example toml files (as we have in kohya_ss gui) as a starting point to tweak, and a nice place for some documentation.
> > 
> > 
> > 
> > 1. Kohya are the scripts used for training, the web UI is called bmaltais
> > 2. There isn't much that needs to be changed on this trainer compared to bmaltais's from my experience
> 
> Kohya_ss gui as I mentioned vs Kohya sd-scripts or did you not see that?
> 
> Where is the documentation on this? Where are the popups (one had one popup) for this? Seriously, when answering do help as I asked for documentation on these not "There isn't much that needs to be changed" when I start it and most stuff is not checked and uses nomenclature I have not seen in Kohya_ss gui before.

There are tooltips if you idle the cursor into the field you want to know the info about.

**Comment by DarkAlchy** [comment]
Only one tooltip did I find (helped too) and the others never had one I tried as I needed help with them.

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/10561690/029259c1-aa16-459d-9572-8a27a7590637)

An example as Tucker had a popup but none of the rest did.

**Comment by Jelosus2** [comment]
> Only one tooltip did I find (helped too) and the others never had one I tried as I needed help with them.
> 
> ![image](https://private-user-images.githubusercontent.com/10561690/316271528-029259c1-aa16-459d-9572-8a27a7590637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMzI1ODcsIm5iZiI6MTcxMTIzMjI4NywicGF0aCI6Ii8xMDU2MTY5MC8zMTYyNzE1MjgtMDI5MjU5YzEtYWExNi00NTlkLTk1NzItOGEyN2E3NTkwNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIyMTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNzAwMWI5MmVjYzU4NmYyNTkyMzNlZmZlYjdlZDg5MmE1ZWM4OWQ3YzhhYWE3NzdlODJjODk3OTQwZjNmZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jbyrXXZ0zMCrpM147tDJf30eEVEsPMiAPWraOkxkFk)
> 
> An example as Tucker had a popup but none of the rest did.

Those are pretty new because in the version of the trainer I'm using i don't have that so I think you shouldnt worry about that, other fields should have tooltips because I have them on my trainer.

**Comment by DarkAlchy** [comment]
Thing is I use DoRA now with lokr.  I know what train norm is (kinda, but it is in the gui).  Rescale no idea because Constrain is there.  Some of the values I have in the gui are greyed out in this too.  Pretty much went back to 22.6.0 kohya_ss gui for now as no one I asked uses this since before XL so could not help.

**Comment by Jelosus2** [comment]
> Thing is I use DoRA now with lokr. I know what train norm is (kinda, but it is in the gui). Rescale no idea because Constrain is there. Some of the values I have in the gui are greyed out in this too. Pretty much went back to 22.6.0 kohya_ss gui for now as no one I asked uses this since before XL so could not help.

I see, well, just wait till Derrian is available, he will probably explain to you what those are

**Comment by derrian-distro** [comment]
> > Thing is I use DoRA now with lokr. I know what train norm is (kinda, but it is in the gui). Rescale no idea because Constrain is there. Some of the values I have in the gui are greyed out in this too. Pretty much went back to 22.6.0 kohya_ss gui for now as no one I asked uses this since before XL so could not help.
> 
> I see, well, just wait till Derrian is available, he will probably explain to you what those are

what I can say is I *also* have literally no clue what those args do nor what their inputs should be, other then their type.

**Comment by derrian-distro** [comment]
and if an arg is grayed out, it's because it doesn't work with other settings you have selected, bmaltais does not do these validation checks, which means in a lot of cases you probably are setting args that are actually invalid.

**Comment by DarkAlchy** [comment]
> and if an arg is grayed out, it's because it doesn't work with other settings you have selected, bmaltais does not do these validation checks, which means in a lot of cases you probably are setting args that are actually invalid.
> 
> regardless, I am still working on more things for the dev branch, and it is _not_ ready for main, tooltips will be added once I am done with all of that

Yeah, bmalt doesn't make sure so a lot of what I input is ignored, or has a detrimental result if used.

**Comment by derrian-distro** [comment]
oh and for the record, I actually do plan on adding example tomls to the repo once I find satisfactory results, for ponyxl, and the 1.x tomls I usually use for my training. They are fairly high effort though, so probably not for everybody

**Comment by DarkAlchy** [comment]
I just deleted pony as I want no part of that (everyone stay away from the Japanese 2.5 pony model as you have now been alerted. 
 Use at your own risk.).  For me I just do XL.

**Comment by Jelosus2** [comment]
> I just deleted pony as I want no part of that (everyone stay away from the Japanese 2.5 pony model as you have now been alerted. Use at your own risk.). For me I just do XL.

What do you mean with "stay away from the Japanese 2.5 pony model"?

**Comment by DarkAlchy** [comment]
Just take the warning, and move on as I am not going to spell it out.  I deleted it so fast living in the USA.

**Comment by Enferlain** [comment]
rescale and constrain are used for oft and boft at least, already forgot what they exactly do tho but you can read about it either in lyco discord or github
