### ISSUE TITLE
How to update ?

### ISSUE THREAD

**Issue by ledahu** [derrian-distro/LoRA_Easy_Training_Scripts#194]
Hi

As i understand, it use de kohya script. How to update it and see/update/change the cuDNN ? 

Thank you

**Comment by Jelosus2** [comment]
Update what? The scripts?

**Comment by ledahu** [comment]
yes, and keep updated all improvement of kohya release . Im noob. Sry if its a stupid question :/

**Comment by Jelosus2** [comment]
I don't recommend updating the scripts because it might break something within the UI

**Comment by ledahu** [comment]
i would like to enable the improvement of cudnn , and it seems they added some different sort of Lora/Lycoris , i'snt a way to add it manually without breaking the UI ?

**Comment by Jelosus2** [comment]
the patch of cudnn was removed because it doesn't give a major improvement now. Regarding the new types of networks you can add them yourself in the UI and scripts if you know what you are doing, else I would suggest either give up or suggest to Derrian the addition of those new networks.

**Comment by Jelosus2** [comment]
He will probably check this issue so you could suggest what you want to be added here

**Comment by ledahu** [comment]
for exemple, kohya seems to have an option to fix the "triton" missing module that occur on some machine (mine )

**Comment by Jelosus2** [comment]
Oh you dont have to worry about that issue in specific. It only errors out but doesn't affect the training

**Comment by Jelosus2** [comment]
Answer was already given so I'm closing the issue
