### ISSUE TITLE
Readme documentation does not explain how to resume a job from a previous LoRA epoch checkpoint

### ISSUE THREAD

**Issue by peteer01** [derrian-distro/LoRA_Easy_Training_Scripts#198]
Apologies if this is not the right places to ask for this request, but I am unable to figure out how to resume training from a saved epoch checkpoint.  Is it possible to update the readme documentation to explain how to use LoRA Trainer to continue training a previous training run?

**Comment by Jelosus2** [comment]
You use this options to save the state of the training
![Screenshot_3](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/75176441/63e1c2e3-869f-450a-a0aa-3b46556dd4b5)
And then when you want to resume you have to input the folder where the state was saved here
![Screenshot_4](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/75176441/fde523b8-e630-4a0c-ad77-ce950a91efff)

**Comment by peteer01** [comment]
That makes sense!  Thank you for sharing that.  It might help others if that can be added to the readme.

**Comment by Jelosus2** [comment]
That depends on him, but I guess he will once the trainer gets an update. Also np, happy to help :)

**Comment by Jelosus2** [comment]
Solved
