### ISSUE TITLE
Not a bug - request for feature

### ISSUE THREAD

**Issue by ZonSoft** [derrian-distro/LoRA_Easy_Training_Scripts#200]
Is it possible to add network_weights feature present in kohya_ss GUI (to continue training)? It would be really useful.

**Comment by Jelosus2** [comment]
I don't know if he will be adding it but as for now you can save the state of a training using the Saving State options at Saving Args and later resuming the training by specifying the path to the folder of the state that is also place in Saving Args

**Comment by ZonSoft** [comment]
Yes, but it requires saving the state preliminary. There is some ready mechanics to avoid that. Very different animal. All I say it's useful.

**Comment by Jelosus2** [comment]
You can always add it yourself before it's added to the trainer oficially

**Comment by ZonSoft** [comment]
Already did - quick and dirty, have no time for better approach - but I strongly believe any good project must have one architect. Job done is of exceprional quality and lots of people may benefit from expanding this solution.

**Comment by Jelosus2** [comment]
If it's benefitial I'm sure he will add it. When? I don't know.

**Comment by derrian-distro** [comment]
ah yeah, I keep forgetting to add that, I had actually *planned* on adding that for a while now, but keep getting distracted by the larger additions
