### ISSUE TITLE
How to run on second GPU?

### ISSUE THREAD

**Issue by trihardseven** [derrian-distro/LoRA_Easy_Training_Scripts#205]
I want to run the training on a second GPU. Any idea how to do that? It always defaults to my main GPU.

**Comment by Jelosus2** [comment]
1. Go to the folder of the trainer.
2. Right click on `run.bat` file and click edit.
3. Replace it's content with
```bat
@echo off

title LoRA Trainer
cd %~dp0
call sd_scripts\venv\Scripts\activate
set CUDA_VISIBLE_DEVICES=1
python main.py
pause
```
4. Save the file and run it again.
5. Enjoy.

**Note:** If it uses the wrong GPU change the line to this set `CUDA_VISIBLE_DEVICES=0`
