### ISSUE TITLE
Issue with the output of training 

### ISSUE THREAD

**Issue by IReDaRX** [derrian-distro/LoRA_Easy_Training_Scripts#206]
I have the dev branch. The training works but when I test the lora it doesn't have any data, I tried generating in the same seed with and without the lora and the images look identical. Also after I finished training the lora I noticed that the epochs all have exactly the same size.

>C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
sdxl_train_network.py
C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
steps:  10%|█████▋                                                   | 58/580 [05:57<53:39,  6.17s/it, avr_loss=0.0527]
saving checkpoint: E:/Newfolder/Trainingsources/output\TanzaXL-000001.safetensors                     train_util.py:3744
                             C:\Users\kirito\Downloads\TrainingEasyLora\LoRA_Easy_Training_Scripts\ba
epoch 2/10                   ckend\runtime_store\config.toml...
steps:  17%|█████████▊                                              | 101/580 [10:02<47:37,  5.97s/it, avr_loss=0.0603]3

**Comment by Jelosus2** [comment]
Well, all the epochs should have the same size, can you share the toml file?

**Comment by IReDaRX** [comment]
> Well, all the epochs should have the same size, can you share the toml file?

Toml file is here: https://pixeldrain.com/u/wUDhmduW

**Comment by Jelosus2** [comment]
I don't see anything wrong with it. Also out of curiosity, you looked the settings your using somewhere?
