### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by captainweasly** [derrian-distro/LoRA_Easy_Training_Scripts#209]
Currently using a 3070ti.

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/115602603/b1d761ac-15ce-4fcd-b533-4a7470e85aff)

**Comment by captainweasly** [comment]
Ineed.

**Comment by Jelosus2** [comment]
Sorry for the delayed reply. Would you mind trying dev branch to see if it fixes the issue? It's more up to date too so should help reducing the memory usage aswell. In case you don't know how to clone the dev branch: `git clone -b dev https://github.com/derrian-distro/LoRA_Easy_Training_Scripts`

**Comment by Jelosus2** [comment]
Hello, any updates on this? It's been two weeks since the last reply so I'm gonna close the issue in 2 days if there's no further response. If you see this when it's closed feel free to open a new issue.

**Comment by captainweasly** [comment]
I will need to retry this weekend since I am out of county and not on my desktop.

**Comment by Jelosus2** [comment]
Any update on this?

**Comment by Jelosus2** [comment]
I'll be closing the issue since it appears to be inactive, feel free to reopen it if you ever need to
