### ISSUE TITLE
Output results not desired

### ISSUE THREAD

**Issue by smasonlawrence** [derrian-distro/LoRA_Easy_Training_Scripts#210]
Hi All, since there isn't a discussion board here I guess I'll have to put this under issues. Anybody able to offer some insight as to how I can improve my quality? I'm just overall not that impressed with the results. toml and output result attached... any suggestions on better settings to improve results?

![vlengies_20240513150310_004500_00](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/104658444/4439ee69-a91e-4c77-a013-7a15d7e140b4)

[vlengies.toml.txt](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/files/15314418/vlengies.toml.txt)

**Comment by Jelosus2** [comment]
Ok, so I have some questions.
1. What are you trying to train?
2. How many images of the concept do you have?

Also is that image generated from the sampling option of the trainer? I see you had it enabled in the toml; if yes then try on the tool you use to generage instead of trainer's sampler.

**Comment by smasonlawrence** [comment]
I'm trying to train the actress Vanessa Lengies, I have 344 images, all high quality and cropped to her head or body.
My captions are similar to this:
vlengies, 1girl, solo, smile, brown hair, realistic, brown eyes, looking at viewer, long hair, lips, grin, teeth, upper body, curly hair

I ran it through SD with the attached out put, its okay.. 

![stable-output](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/104658444/18f1aac2-c9fc-4440-94e0-b57cac9c6db7)

but hardly looks like the spitting image of what she actually looks like.
![photo-reference-of-actress](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/104658444/42beb6fb-7615-40fe-91f1-467fdd23335e)

**Comment by Jelosus2** [comment]
I don't train photorealism so I can't help you further, sorry.

**Comment by smasonlawrence** [comment]
Ok figured it out I think, the sampler in LoRA Easy Training Scripts output looks horrible for some reason, running it through SD with the actual training check point looks 100% better. So the checkpoint of the lora i was using had too many steps, but I couldnt tell that from the sample image that was generated by LoRA ETS. But in SD, I ran it at different strength's and found that it was over baked. So a strength of 0.6 was ideal. Just posting this if anybody else ever has a similar issue, the take away is this:

- Don't trust the sampler in LoRA ETS if training on a different checkpoint that the default SD model.
- Render the actual LoRA in SD to verify output results.
- Always play with the strength to determine if the LoRA is overbaked or not.

Final output image at 0.6 strenth is below, looks a lot better.
![stable-output-0_6](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/104658444/87c78fff-d6f9-4cd1-bcaf-66a328323d55)

**Comment by derrian-distro** [comment]
just a note, the sample code is code kohya, the creator of the underlying system this uses, made. Personally, I don't use samples at all, instead preferring to just test in auto1111 instead.
