### ISSUE TITLE
torch and cudnn problems

### ISSUE THREAD

**Issue by Cookie4Free** [derrian-distro/LoRA_Easy_Training_Scripts#212]
I'm sorry if this is a dumb question. I'm new to this, and I'm trying to learn how to do LoRAs. Most of the settings I imported are from this guide: https://civitai.com/models/22530/guide-make-your-own-loras-easy-and-free

To be honest, I couldn't find any guide on how to use this training script correctly. I'm pretty sure I'm doing something wrong here.

This is the error I get. Triton is only supported for Linux, so I guess I can ignore that one. As for the Torch and cuDNN error, I have no idea what's causing it. Also, 200 hours seems way too long to me—is that normal?

OS Windows 11, rtx4090, amd ryzen 7 5800x3d

```
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\attention_processor.py:1039: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  hidden_states = F.scaled_dot_product_attention(
NaN found in latents, replacing with zeros
B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
steps:   0%|                                                    | 1/2460 [03:45<154:14:03, 225.80s/it, avr_loss=0.0121]NaN found in latents, replacing with zeros
steps:   0%|                                                       | 2/2460 [09:49<201:06:49, 294.55s/it, avr_loss=nan]
```

**Comment by Jelosus2** [comment]
Hello, seems your using the version of the main branch. Am I right?

**Comment by Cookie4Free** [comment]
To be honest, I don't really know—I think so. I followed the instructions in readme on how to install it.

**Comment by Jelosus2** [comment]
Ok. Try to install the dev branch. `git clone -b dev https://github.com/derrian-distro/LoRA_Easy_Training_Scripts`

**Comment by Cookie4Free** [comment]
I'm sorry for beeing such a noob 😓 How exactly do I get to the dev branch?

**Comment by Cookie4Free** [comment]
The time has significantly dropped, thanks.
But about the other errors, do I have to do anything about them?
And in general, are there any good guides for how to do the settings the best way or presets that I can download?

`steps:   0%|                                                                                  | 0/2460 [00:00<?, ?it/s]
epoch 1/10
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\attention_processor.py:1039: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  hidden_states = F.scaled_dot_product_attention(
NaN found in latents, replacing with zeros
B:\Stable_Diffusion\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
steps:   0%|                                                      | 1/2460 [00:33<23:10:26, 33.93s/it, avr_loss=0.0107]NaN found in latents, replacing with zeros
steps:   0%|                                                         | 2/2460 [01:06<22:41:44, 33.24s/it, avr_loss=nan]`

**Comment by Jelosus2** [comment]
Ok, you said your GPU is a RTX 4090 right?
1. In what version of SD you want to train?
2. About the NaN errors. If you see `avg_loss=nan` while training it means the LoRA is ruined.
3. While training does the shared memory of your GPU raise?
4. Please show your toml config file.

**Comment by Jelosus2** [comment]
What are you targeting to train? A character, style, concept?

**Comment by Cookie4Free** [comment]
I wanted to train a style. I also wanted to create a character later on after this project.

**Comment by Jelosus2** [comment]
Do you have Discord?

**Comment by Cookie4Free** [comment]
Yes, I do. Same name as here: Cookie4Free

**Comment by Jelosus2** [comment]
Did it get solved?
