### ISSUE TITLE
Error resuming state for DORA training

### ISSUE THREAD

**Issue by herrotarou** [derrian-distro/LoRA_Easy_Training_Scripts#213]
![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/171110324/6f96e150-7e5b-44fc-8df1-a5e8e15e7c99)
The custom state_dict can't load due to ".dora_scale" being unexpected keys.

**Comment by Jelosus2** [comment]
That looks like an error from sd_scripts to me and not the UI itself. Only thing Derrian can do is update them if there's a working version of the scripts for that issue.

**Comment by derrian-distro** [comment]
it's not possible to resume the state of a DoRA as it uses keys that are not present in normal lora
