### ISSUE TITLE
SD 3 support

### ISSUE THREAD

**Issue by alexgit256** [derrian-distro/LoRA_Easy_Training_Scripts#216]
Diffusors now [support Stable Diffusion 3](https://github.com/chenbaiyujason/sd3_diffusers/blob/main/examples/dreambooth/README_sd3.md). Some people have already have trained [SD 3 LoRAs](https://civitai.com/models/514524/sd3-close-up-of-anime-light-and-shadow?modelVersionId=571802).
ComfyUI already supports LoRAs. One can test it using the [following workflow](https://comfyworkflows.com/workflows/8cf4c8b7-4970-4827-b5fb-36dc1a4409b8). It would've been great to train these using your UI.

**Comment by Jelosus2** [comment]
Sorry, but we must wait until there's a stable release of sd-scripts implementation for SD3 LoRA training. The model has been out for 4 days and some settings doesn't work due to it's architecture.

**Comment by derrian-distro** [comment]
As far as I know, kohya is working on a lora implementation in sd-scripts, as there is a basic inference script for SD3 in a branch for it. I'll make sure to add it as soon as sd-scrupts supports it, or, if kohya decides to drop support for it, find some way to add it via diffusers

**Comment by alexgit256** [comment]
It seems that kohya now [supports](https://github.com/kohya-ss/sd-scripts/tree/sd3) SD 3. The code is probably still raw and arguably has [some issues](https://github.com/kohya-ss/sd-scripts/issues/1390) with large datasets, but still should work just fine.
Thank you for your project. Can't wait to train LoRAs for SD 3 using your GUI!

**Comment by Jelosus2** [comment]
Hello, that's great news but I think we should wait until is merged into main branch, hence being more stable

**Comment by Jelosus2** [comment]
Nvm, seems Derrian will create a branch for sd3 experimental features, apologies for the confusion.

**Comment by derrian-distro** [comment]
It seems that kohya is now actually trying to add LoRA support to SD3 and Flux.1 so I will be getting to updating the UI (in it's own branch for now) soon enough.

**Comment by derrian-distro** [comment]
closing this as flux is available for training in the flux branch
