### ISSUE TITLE
Change of backend port over the UI - dev branch

### ISSUE THREAD

**Issue by Koschpa** [derrian-distro/LoRA_Easy_Training_Scripts#217]
Hi, 
it would be nice to change the backend port in the gui.
On my PC, Incredibuild is running on Port 8000 and so the backend wasn't able to create the server.
There wasn't even an error code.

I fixed it on my side.
Just a feature request.

PS: the dev branch is awsome and much better then the main.

**Comment by Jelosus2** [comment]
It would be convenient to have such option in the `config.json` file for those cases yea. Let me ask Derrian about this.

**Comment by Panchovix** [comment]
+1 to this. I have multiple GPUs, so I want to run some training in parallel but no dice, even if i change the 8000 ports to 8001 for example on the code, still calls or works only on port 8000 for some reason.

**Comment by Jelosus2** [comment]
> +1 to this. I have multiple GPUs, so I want to run some training in parallel but no dice, even if i change the 8000 ports to 8001 for example on the code, still calls or works only on port 8000 for some reason.
> 
> `HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /validate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001854B56D7C0>`

Make sure you the port 8001 is available, that you changed it in the code and you also changed it into the UI's box where input the connection string (box above "start training" button.

**Comment by Panchovix** [comment]
> > +1 to this. I have multiple GPUs, so I want to run some training in parallel but no dice, even if i change the 8000 ports to 8001 for example on the code, still calls or works only on port 8000 for some reason.
> > `HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /validate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001854B56D7C0>`
> 
> Make sure you the port 8001 is available, that you changed it in the code and you also changed it into the UI's box where input the connection string (box above "start training" button.

Made sure about all of them, well searched :8000 on VS code on the main folder and replaced all with :8001 after installing the backend.

**Comment by Jelosus2** [comment]
The latest update in dev branch has allowed the option to add a port in the config.json
