### ISSUE TITLE
Add Pony support?

### ISSUE THREAD

**Issue by SirMoogle** [derrian-distro/LoRA_Easy_Training_Scripts#219]
This script has been a godsend for training LoRAs for me, so thank you very much for this. I was wondering if it'd be possible to add an option for training LoRAs for Pony models, as I hear there are some differences from the SDXL training scheme.

**Comment by Jelosus2** [comment]
Nope, there are no differences, I myself train Pony LoRAs on this scripts, just make sure to clone the dev branch version of the trainer for more improvements. Here's the command: `git clone -b dev https://github.com/derrian-distro/LoRA_Easy_Training_Scripts`
