### ISSUE TITLE
Use PowerShell instead of Batch for Windows?

### ISSUE THREAD

**Issue by robertsmieja** [derrian-distro/LoRA_Easy_Training_Scripts#22]
PowerShell 5 comes installed with all supported Windows versions iirc, and since you are using it anyways and depending on it for stuff like `curl` aliases (as `curl` is NOT installed on Windows by default), why not use it instead?

**Comment by derrian-distro** [comment]
I haven't used powershell because, well, I hate it. It's one of the most annoying languages that I have ever tried to use, and honestly, I don't know how to use it.

and from what I read, curl comes pre-installed on pretty much every version of windows 10 and every version of windows 11

**Comment by derrian-distro** [comment]
but, if you can give me a guide on how to use powershell then I can give it a shot. I'm currently trying to write up an installer for the new update, which the v4 installers no longer support

**Comment by robertsmieja** [comment]
I don't have a good tutorial site handy, but you can try https://powershellbyexample.dev/

The crash course on syntax:
- `#` starts a comment
- `$` starts a variable
- Everything is in `Verb-Noun` syntax, i.e. `Get-Command`, `Get-Help`
- Everything returns objects
- `Write-Host` is the same as `echo`
- `Get-Command` is the same as `which` and returns where an exe/cmd comes from
- `Get-Help <cmd>` returns man pages
- VSCode is the recommended IDE/editor

---

I wrote an "installer" for my K3s cluster that covers the rough functionality you already have - https://gist.github.com/robertsmieja/efbce72587607e5aefde6e63e540a45e

The important parts that you can use as a reference: 
- `Test-Requirements` which checks if `helm` and `kubectl` are available on the command line path - https://gist.github.com/robertsmieja/efbce72587607e5aefde6e63e540a45e#file-common-psm1-L3
- the `installK3sOnRemote`'s script argument, which populate pwsh's help text - https://gist.github.com/robertsmieja/efbce72587607e5aefde6e63e540a45e#file-installk3sonremote-ps1-L3
- `installSecret.ps1` which sets an environment variable, and stores the string result of a raw command (`bw get ...`) into a variable

As a bonus PowerShell can run on Linux/Mac so it's multi-platform

**Comment by derrian-distro** [comment]
Alright thanks, I'll look into improving the installers once I get the hang of powershell

**Comment by robertsmieja** [comment]
I think it would also be fair to do the install in Python, and assume the users of this repo at least have enough technical knowledge to run a Python script.

Not sure why that didn't occur to me first.

**Comment by derrian-distro** [comment]
I don't know why it didn't occur to me either, I'll look into it.
