### ISSUE TITLE
Numpy 2.0 issue

### ISSUE THREAD

**Issue by Geel713** [derrian-distro/LoRA_Easy_Training_Scripts#220]
I'm new on github sorry if this is not belong to here.

Last week I was able to use it now it says from shioboken6 import Shioboken line 27 raising an error.
The first line of the command line is: A module that was compiled using NumPy 1.x cannot be run in.
I checked last week there was a numpy 2 release so its probably it.
I don't know if the issue is on my end or not, I added the whole error in attachment

![numpy2error](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/173645348/13ae1775-9b2c-4665-9e04-df0a5ee76cec)

**Comment by Jelosus2** [comment]
Yea, we probably will need to pin the version of numpy. As hotfix you can activate the venv (virtual environment) and run `pip install numpy<2`, answer with `y` the prompt and done, should be fixed.

**Comment by Jelosus2** [comment]
Any update? I will close the issue in the next few days if there's no response
