### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by jetsletmethehellin** [derrian-distro/LoRA_Easy_Training_Scripts#221]
I have a feeling this has to do with my numpy version but I've tried three different versions <2 and I keep getting this. Would it be possible to figure out which precise version is expected? (I'm pretty entry-level so I'm probably missing something blatantly obvious.)

**Comment by Jelosus2** [comment]
Are you using main or dev branch?

**Comment by jetsletmethehellin** [comment]
Main I think? Whatever's in Releases. "UI Release v1".

**Comment by Jelosus2** [comment]
That's main branch, could you try the dev version? The installation process is almost the same:
1. Run `git clone -b dev https://github.com/derrian-distro/LoRA_Easy_Training_Scripts`
2. Execute the `install.bat` file.

**Comment by jetsletmethehellin** [comment]
That one just crashes as soon as I try to open the UI without any warning. Could just be that my PC's too old for this sort of thing, which was something I entertained from the start.

**Comment by jetsletmethehellin** [comment]
Nope, the whole command prompt just closed on me without warning. This was only with the dev version for the record; the other opens fine, it just gives me this error when I try to train with it.

**Comment by Jelosus2** [comment]
that permission is to allow all install without problems. On a different note, what GPU do you have and how much RAM?

**Comment by jetsletmethehellin** [comment]
32 GB RAM, but the GPU is an old 1080Ti.

**Comment by Jelosus2** [comment]
should still be ok, hmm, could you try reinstalling but this time allowing the admin prompt?

**Comment by jetsletmethehellin** [comment]
Hmm... What precisely does the admin prompt allow the installation to do? And do those permissions persist beyond the install process, either for the trainer or for anything else that uses Python?

**Comment by Jelosus2** [comment]
It executes a command that disables temporarily the execution policy so all the scripts can be installed correctly without issue because on Windows sometimes there's cases of scripts that couldn't be installed correctly because the execution policy was enabled and restricted. And for the second question, it doesn't persist after the execution policy is disabled.

**Comment by jetsletmethehellin** [comment]
So it's basically just like when an installer for any other program asks permission during install.

Hmmm... I'll consider it. As I'm not a particularly experienced programmer, anything involving a command prompt still gives me a bit of unreasonable anxiety, so something that runs through command prompt asking for shell permission sets off alarms in my brain just by matter of course. I know it's unreasonable, but I'm that way, haha.

If I do decide to do it, I'll report back with results.

**Comment by Jelosus2** [comment]
I mean, a lot of people use this UI (myself included) and I can assure you that it has no malware, and even more because you can check the code here. It's open source so anyone can check the code, and if they found something suspicious there would be reddit posts and all of that already.

**Comment by derrian-distro** [comment]
> Hmm... What precisely does the admin prompt allow the installation to do? And do those permissions persist beyond the install process, either for the trainer or for anything else that uses Python?

https://github.com/kohya-ss/sd-scripts?tab=readme-ov-file#windows-required-dependencies
kohya requires this to be done for windows, and as much as I wanted to get around it, I couldn't

**Comment by jetsletmethehellin** [comment]
Hmm. That's a good point actually. Well, like I said, I'll try to get over my anxiety and do it. I know I'm being unreasonable, it's just one of those things where my subconscious won't listen to my conscious brain, like agoraphobia or what have you. 😅

**Comment by jetsletmethehellin** [comment]
Okay! I went ahead and set the fears aside and redid the dev install with permissions granted. The UI did load but training failed; I got these errors:

**During Install:**
DEPRECATION: LoraEasyCustomOptimizer is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option.

Traceback (most recent call last):
  File "<...>\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'default_config.yaml' -> '<...>\\.cache\\huggingface\\accelerate\\default_config.yaml'

OSError: Can't load tokenizer for 'openai/clip-vit-base-patch32'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-base-patch32' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**During Load of UI:**
<...>\backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
<...>\backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
<...>\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

Traceback (most recent call last):
  File "<...>\LoRA_Easy_Training_Scripts\backend\main.py", line 19, in <module>
    tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")
  File "<...>\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-base-patch32'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-base-patch32' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**During Training:** HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /validate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4D285EA10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

The last one is particularly weird. I'd guess it's caused by my firewall somehow but... _how_, given that the connection is literally coming from the computer itself, I wouldn't know.

**Comment by Jelosus2** [comment]
Ok, for the "The system cant move the file to a different hard drive" you have to go to `C:/Users/YOUR_USER/.cache/huggingface` and you should see a file with no extension called `accelerate`, delete it and run the installer again.

**Comment by jetsletmethehellin** [comment]
Yep! No error there this time. The load errors and the weird connection issue are still there though. Connection issue was happening when I tried Kohya, too, so pretty sure that's on my end but it makes no sense to think my firewall would be blocking a connection from my own computer.

**Comment by Jelosus2** [comment]
The tokenizer and connection refused errors you mean?

**Comment by jetsletmethehellin** [comment]
Yep. All the stuff listed under During Load of UI and During Training.

**Comment by Jelosus2** [comment]
the connection issue is not because of the firewall

**Comment by jetsletmethehellin** [comment]
I'm out of time to focus heavily on things just now, but I'll do that as soon as my schedule frees up again. I appreciate all the patience! I know it must be annoying dealing with a programing noob, haha.

**Comment by jetsletmethehellin** [comment]
Alright, in the process but it's saying requirements.txt doesn't exist ("no such file or directory").

I assumed it was the same from the main folder so I copy-pasted that into the directory I'm working in but it then said the file from line 42 of requirements.txt "does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found."

**Comment by Jelosus2** [comment]
Do you have a Discord account? If so, we can talk there, would be easier and more comfy. My username is Jelosus1, you can send me friend request and Ill help you troubleshoot your problems :)

**Comment by jetsletmethehellin** [comment]
Yeah, though I only use it as a Civitai account, haha. I'll see if I can figure it out and send you a request. Thanks again for all your patience!

**Comment by jetsletmethehellin** [comment]
Update: Resolved via Discord!
