### ISSUE TITLE
LoKr Settings

### ISSUE THREAD

**Issue by Verun11** [derrian-distro/LoRA_Easy_Training_Scripts#223]
I noticed on kohya_gui LoKR has a few options that are missing from this UI when using the LoKr format
I'd prefer to use easy scripts but I dont see any way to access them like an optional arg field. Main one that's needed is LoKr factor since that affects the dim
![220535](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/163819933/28419e55-84b5-473d-bf55-369c658d9a3a)

**Comment by Jelosus2** [comment]
As far as I know those aren't needed, and Lokr is barely used since other networks outperform it.

**Comment by Verun11** [comment]
Thanks. Which would you recommend instead?

**Comment by Jelosus2** [comment]
What are you trying to train?

**Comment by Verun11** [comment]
just an image Lora

**Comment by Jelosus2** [comment]
then use DoRA (5% better than LoRA) or LoRA
