### ISSUE TITLE
install instructions outdated

### ISSUE THREAD

**Issue by yggdrasil75** [derrian-distro/LoRA_Easy_Training_Scripts#227]
the install.sh script is no longer available. the instructions dont download a sd_scripts subfolder download to go into.

**Comment by derrian-distro** [comment]
I didn't have time to update the readme yet. I'll be updating it when I have time

**Comment by sabertrtr** [comment]
So.... there is no way to install this, then?

**Comment by Jelosus2** [comment]
> So.... there is no way to install this, then?

If your using the latest commit on main branch just do this
Linux:
```sh
# If you have python 3.10 installed
./install310.sh

# If you have python 3.11 installed
./install311.sh
```

Windows:
Double click the install.bat file and allow the admin privileges for PowerShell when it prompts for it.

If you want to run the trainer on your own GPU answer the question `Are you using this locally (y/n)` with **y**

**Comment by derrian-distro** [comment]
the install instructions have been updated to reflect the new format.
