### ISSUE TITLE
How to train on other serveur (not locally)

### ISSUE THREAD

**Issue by manuiageek** [derrian-distro/LoRA_Easy_Training_Scripts#230]
First of all, thanks for making this useful utility to make lora ! I love it <3 ! 

Here is my question : is there a way to train my lora on other server ? (like runpod or something to "rent" a better GPU ?).

I saw that you can save the derrian-distro/lora_easy_training_scripts configuration of lora into toml files. Is there some kind of command to be able to load and execute that toml file into kohya-ss sd script ? Or maybe there's a way to use directly derrian-distro with command line once you get the toml file ready with the pyside program ?

**Comment by derrian-distro** [comment]
You would install the backend (found [here](https://github.com/derrian-distro/LoRA_Easy_Training_scripts_Backend)) to the server, and run one of the included tunnel services. Keep in mind that some of the gpu services don't like tunnels, so make sure to look for anything relating to that before trying.
Afterwards, just connect to the backend using the front-end installed on your computer by changing the URL to the provided url

**Comment by Jelosus2** [comment]
In addition to what Derrian said if your service can run jupyter notebooks you can take a look at the code of my colab for reference: https://github.com/Jelosus2/Lora_Easy_Training_Colab

**Comment by Jelosus2** [comment]
I'll be closing this as the references are given, if you need further help please feel free to open another issue
