### ISSUE TITLE
When I press start nothing happens

### ISSUE THREAD

**Issue by malksama** [derrian-distro/LoRA_Easy_Training_Scripts#231]
![ezgif-4-375a4f5258](https://github.com/user-attachments/assets/a4da1480-36f3-4eb2-96b0-79a5de2dd2d3)

**Comment by Jelosus2** [comment]
I've seen a lot of people getting this and the solution was doing this steps:
- Place yourself in the directory of the trainer, then go to backend folder
- Open Terminal in the backend folder -> run `.\venv\Scripts\activate` -> run this commands in order:
```
pip install -U -r requirements.txt
pip install -U ../custom_scheduler/.
pip install -U -r ../requirements.txt
```

**Comment by derrian-distro** [comment]
this actually looks like they just didn't install the backend. make sure you clone the project, then run your respective installer

**Comment by Jelosus2** [comment]
I've seen people with the backend installed still having this issue. Don't know the reason, I just know it works lol

**Comment by malksama** [comment]
![image](https://github.com/user-attachments/assets/838d4317-f667-446c-af93-56a5981eba9a)
I install it in this path right?

**Comment by malksama** [comment]
@derrian-distro 
![image](https://github.com/user-attachments/assets/a0078556-8521-46dd-8fea-a8a8f64dd2ec)
I downloaded it twice but the backend folder is already empty no matter how hard I try to install the app again.

**Comment by derrian-distro** [comment]
did you follow the install instructions as listed on the readme?
the way you install it is git clone -> run install.bat -> say y to the question of if you are using it locally

**Comment by malksama** [comment]
Should I have said "Y" even if I didn't have one?

**Comment by Jelosus2** [comment]
> Should I have said "Y" even if I didn't have one?

To install the backend you have to:
1. Clone the repository
2. Run the `install.bat` file
3. To the question `Are you using this locally (y/n)` answer with **y** if you want to train locally on your own GPU.

**Comment by malksama** [comment]
I have to press y when it asks me "Are you using this locally (y/n)" because if I press n it will never load the backend
even though I don't use webui locally

**Comment by malksama** [comment]
**Ok I installed the backend but still getting the same error**

**Comment by malksama** [comment]
@Jelosus2 As for the method you suggested to me, the commands do not work except for this "pip install -U -r requirements.txt"
![image](https://github.com/user-attachments/assets/fa3af14d-e0c7-41ec-b348-69189a1f3874)

**Comment by derrian-distro** [comment]
are you following the install instructions stated [here](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts?tab=readme-ov-file#windows)? it still looks like you haven't installed the backend

**Comment by malksama** [comment]
I followed all those instructions and installed backend

**Comment by Jelosus2** [comment]
Do you have a Discord account? I feel it should be easier there. My name there is Jelosus1, add me as a friend and we can discuss this further

**Comment by malksama** [comment]
@Jelosus2 I was going to suggest the same thing
My name there is "sylphysylphiette"

**Comment by malksama** [comment]
@derrian-distro I found out that there is no 8000 port in my computer so I can create one by this command in Python "python -m http.server 8000" 
When I do that the problem changes to this : 
![image](https://github.com/user-attachments/assets/ca1e74bc-be20-4da9-805c-8d6495a7d453)

**Comment by malksama** [comment]
Since I was only testing whether it will start making lora or not, I did not add a database and after I added it the problem did not recur and it is supposed to start making, so where do I monitor the making of lora?

**Comment by Jelosus2** [comment]
Solved on Discord

**Comment by LoRAMilkshake** [comment]
> Solved on Discord

sorry, what was the solution? months ago I managed to install and run the program, but now I'm having the same problem of "NewConnectionError: port 8000 refused". I tried reinstalling with your instructions but now on top of the original problem I'm getting "Module ctypes not found"

**Comment by Jelosus2** [comment]
It's not the same problem, how are you installing the trainer?

**Comment by LoRAMilkshake** [comment]
1) git clone https://github.com/derrian-distro/LoRA_Easy_Training_Scripts.git
2) cd LoRA_Easy_Training_Scripts/
3) #if you are using python 3.11
sh -c "$(wget https://raw.githubusercontent.com/derrian-distro/LoRA_Easy_Training_Scripts/main/install311.sh -O -)"

after the installation, (naturally I selected Y on the question about local use), when I run the program, I get:

HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /validate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e179540>: Failed to establish a new connection: [Errno 61] Connection refused')) 

Now, seems like the install310.sh script did the job, but I hope you guys take the time to check what's happening with the 3.11 version of the installer, because I tried 5 times and that one is a bust

**Comment by Jelosus2** [comment]
The only difference between the install310.sh and the install311.sh files is the python versions used to run the installer. Could you provide info of what OS you are using and it's arch?
