### ISSUE TITLE
"factor" as an option (?)

### ISSUE THREAD

**Issue by Enferlain** [derrian-distro/LoRA_Easy_Training_Scripts#232]
Other than lokr and boft not sure if it appears in any other network

https://github.com/KohakuBlueleaf/LyCORIS/blob/8ad8000efb79e2b879054da8c9356e6143591bad/lycoris/functional/general.py#L14
imported by modules.lokr

https://github.com/KohakuBlueleaf/LyCORIS/blob/8ad8000efb79e2b879054da8c9356e6143591bad/lycoris/functional/general.py#L59
imported by modules.boft

It seems like in boft case there is some automatic parts to the process based on dim, but for lokr I tried various setups and it always stays at -1

**Comment by Enferlain** [comment]
also here

https://github.com/KohakuBlueleaf/LyCORIS/blob/8ad8000efb79e2b879054da8c9356e6143591bad/docs/API.md?plain=1#L56

**Comment by derrian-distro** [comment]
added a way to specify arbitrary network args on the flux branch, this will eventually be merged into main

**Comment by Enferlain** [comment]
pog
