### ISSUE TITLE
what version of torch is being used for the flux training

### ISSUE THREAD

**Issue by zethfoxster** [derrian-distro/LoRA_Easy_Training_Scripts#233]
its been found that this version below increases training speed and reduces vram usage are we currently on this?

torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu124

**Comment by Jelosus2** [comment]
It uses the latest (aka 2.4.0 and 0.19.0). You can always check a package version by going to `(Trainer)/backend/sd_scripts`, opening a cmd in that directory and executing this commands in order:
```
# Windows
.\venv\Scripts\activate
# Linux
./venv/bin/activate

# Windows
pip list -v | findstr package-name
# Linux
pip list -v | grep package-name
```
