### ISSUE TITLE
SDXL training disables clipskip

### ISSUE THREAD

**Issue by zethfoxster** [derrian-distro/LoRA_Easy_Training_Scripts#239]
while its true it does not require it for NORMAL sdxl...pony is sdxl based and is trained on clipskip 2 for best results...can that remain as a hover over tooltip but dont grey out the ability to do it please?

**Comment by Jelosus2** [comment]
pony is SDXL based and clip skip doesn't work there, I'm not sure what do you mean as grayed out because I can still set it tho

**Comment by zethfox** [comment]
Pony specifically is clip Skip 2 ...https://civitai.com/models/257749/pony-diffusion-v6-xl... The very first line in the description even states why. But yeah, when I select the SDXL config checkbox it grays out the clip skip entry box. You can't click into it to edit the number. So you can get to it by manually editing the config in notepad. But that defeats the purpose of having it in the GUI lol

**Comment by Jelosus2** [comment]
Ok yea, I checked it and it does indeed grey out but training with clip skip is not the same that generating with clip skip. I never had any issue with pony training and I too generated on clip skip 1, didn't make any difference.

**Comment by derrian-distro** [comment]
kohya automatically sets the clip skip to 2 as the first layer of SDXL is completely empty, it works as intended, thus greying the value out.
