### ISSUE TITLE
Got this when using Flux Branch

### ISSUE THREAD

**Issue by guy907223982** [derrian-distro/LoRA_Easy_Training_Scripts#240]
Got this when using Flux Branch, not really sure what it means:

Traceback (most recent call last):
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\flux_train_network.py", line 411, in <module>
    trainer.train(args)
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 537, in train
    unet.to(accelerator.device, dtype=unet_weight_dtype)  # this seems to be safer than above
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "C:\StableDiffusion\StableDiffusion\EasyTrainerFlux\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1167, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

**Comment by derrian-distro** [comment]
make sure you have installed the flux branch from scratch as torch 2.4.0 changed a lot. (and broke a lot).

**Comment by guy907223982** [comment]
> make sure you have installed the flux branch from scratch as torch 2.4.0 changed a lot. (and broke a lot).

I reinstalled the flux branch 3 times and torch, I'm still getting this. Any other recommendations?

**Comment by derrian-distro** [comment]
it might be an issue with your config, because I am not able to replicate this error, can you send the toml of your configuration settings?

**Comment by guy907223982** [comment]
> it might be an issue with your config, because I am not able to replicate this error, can you send the toml of your configuration settings?

[1FluxLoraStyle.zip](https://github.com/user-attachments/files/16830065/1FluxLoraStyle.zip)

**Comment by DalleDTIYS** [comment]
Also running into this issue on a fresh install

**Comment by guy907223982** [comment]
> Also running into this issue on a fresh install
> 
> Update: got passed this error by using these models:
> 
> Base Mode: https://civitai.com/models/622579/flux1-dev-fp8
> 
> Ae Model: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors Clip L Model: https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/clip_l.safetensors T5 Model : https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp8_e4m3fn.safetensors
> 
> But now I'm running into this error:
> 
> > Traceback (most recent call last):
> > File "C:\LoraTrainer\LoRA_Easy_Training_Flux\backend\sd_scripts\flux_train_network.py", line 411, in 
> > trainer.train(args)
> > File "C:\LoraTrainer\LoRA_Easy_Training_Flux\backend\sd_scripts\train_network.py", line 595, in train
> > t_enc.text_model.embeddings.requires_grad_(True)
> > File "C:\LoraTrainer\LoRA_Easy_Training_Flux\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1729, in **getattr**
> > raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'")
> > AttributeError: 'T5EncoderModel' object has no attribute 'text_model'

Does that cache/ load the images or does the error happen before?

**Comment by DalleDTIYS** [comment]
Ah ok I just had to change these settings:

Network args > Train on = "Unet Only"
and enable Cache TE Outputs

Seems to be training now! We'll see about results yet :p

**Comment by Jelosus2** [comment]
That is in fact how you should do it, unet only and cache te outputs

**Comment by DalleDTIYS** [comment]
I was getting some extremely noisy looking results so I went through each property step by step in the JSON posted here: https://civitai.com/articles/7009/flux1-d-lora-on-a-12-gb-vram-train-settings-kohyass-web-ui and finally got a Lora result that works really well!

Attched the .toml file as well.

Goodluck and hope this helps!

[flux_toml.zip](https://github.com/user-attachments/files/16831047/flux_toml.zip)

**Comment by guy907223982** [comment]
> Ah ok I just had to change these settings:
> 
> Network args > Train on = "Unet Only" and enable Cache TE Outputs
> 
> Seems to be training now! We'll see about results yet :p

Interesting, that fixed it for me/
