### ISSUE TITLE
Getting this Error. Help?

### ISSUE THREAD

**Issue by PheonixAi420** [derrian-distro/LoRA_Easy_Training_Scripts#241]
![Screenshot 2024-09-09 145701](https://github.com/user-attachments/assets/8f5797c1-93f0-4d92-b29f-cecf24dbcafc)

Anyone know how to fix this error?

**Comment by derrian-distro** [comment]
you need to load the full bf16 model found [here](https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main)
yes, even if you have fp8 selected.

additionally, are you using the correct branch? and if so, do you have the flux section of the args at the bottom of the arg list enabled, and all of the model fields there filled out correctly? Note that you must also have the full fp16 version of the T5 found [here](https://huggingface.co/stabilityai/stable-diffusion-3-medium/tree/main) in order for it to load properly

**Comment by PheonixAi420** [comment]
Okay about the full bf16 I will try that. Im not sure what you mean  by branch. I just ran the application and use a config toml someone else made and changed the directories for my dataset. I do also have the t5 fp16 as well. I was trying to use the fp8 version but you are saying not too so I wont. I have this in my Kohya SS folder if that helps in anyway? I dont have the flux branch of Kohya because I tried installing it about 20 times and kept getting errors so someone suggested this app.

**Comment by derrian-distro** [comment]
in order to train on flux you must install flux branch of my UI, it doesn't support it on main, just follow the install instructions [here](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/tree/flux?tab=readme-ov-file#windows) in order to install the correct version of the scripts, as it is currently experimental.

**Comment by PheonixAi420** [comment]
Okay I will try that thanks

**Comment by PheonixAi420** [comment]
@derrian-distro is this something I should be worried about?
![Screenshot 2024-09-09 184536](https://github.com/user-attachments/assets/92402ba7-0d25-493f-9161-cbbd9f3a90bb)

**Comment by PheonixAi420** [comment]
@derrian-distro I just want to say Thank You, I have tried several different apps/software to get this Flux training working and I did get it started thanks to your advice. I appreciate it. Wasnt sure what the "split qkv" option was so I didnt check it although I did check "split mode"

**Comment by derrian-distro** [comment]
> @derrian-distro is this something I should be worried about? ![Screenshot 2024-09-09 184536](https://private-user-images.githubusercontent.com/170890859/365835752-92402ba7-0d25-493f-9161-cbbd9f3a90bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzQyMDQsIm5iZiI6MTcyNTkzMzkwNCwicGF0aCI6Ii8xNzA4OTA4NTkvMzY1ODM1NzUyLTkyNDAyYmE3LTBkMjUtNDkzZi05MTYxLWNiYmQ5ZjNhOTBiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwMjA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzA0NmM3OGViYjRiMmFjZDk3YzQ5M2NhYjc2NTQ5MzdmZDhhMGU1MzE3NWMzZDM0NWZlNGFjZDUwMGRkYTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NlIgLxtlZ0nGEXKINYKJ_5Vj8SMRflmRbcYPkhKJ_UU)

those errors are normal, they are just warnings, nothing to worry about

**Comment by derrian-distro** [comment]
> @derrian-distro I just want to say Thank You, I have tried several different apps/software to get this Flux training working and I did get it started thanks to your advice. I appreciate it. Wasnt sure what the "split qkv" option was so I didnt check it although I did check "split mode"

glad you got it working!
