### ISSUE TITLE
[suggestion] add option to start next item in queue automatically after the last one is finished

### ISSUE THREAD

**Issue by Hugs288** [derrian-distro/LoRA_Easy_Training_Scripts#251]
if there is already an option for this somewhere i couldnt find it

**Comment by Jelosus2** [comment]
It should be automatic already

**Comment by Hugs288** [comment]
that's weird, for me it stopped after the first one was completed, ill reopen if i manage to replicate it

**Comment by derrian-distro** [comment]
you have to have something in the queue before you start training in order for it to continue training automatically
