### ISSUE TITLE
Sample Args generator assumes SD1 Resolutions/CFG

### ISSUE THREAD

**Issue by DarkPulse** [derrian-distro/LoRA_Easy_Training_Scripts#253]
I'm trying to train some SDXL LoRAs using the scripts (Because for some reason Kohya's GUI is wigging out on my system for reasons I don't understand... some weirdness with Pydantic), and I was wondering why the samples it was generating were so... _**WRONG.**_

Then I realized why when I checked the command prompt.

```
INFO     height: 512                                                              train_util.py:5286
INFO     width: 512                                                               train_util.py:5287
INFO     sample_steps: 30                                                         train_util.py:5288
INFO     scale: 7.5                                                               train_util.py:5289
INFO     sample_sampler: dpm_2                                                    train_util.py:5290
```

In short... the Sampler has had all of its parameters completely hardcoded in the Python file, so it generates a SD1-resolution sample, and will never, ever look right. This makes it functionally worthless for SDXL, Pony, Illustrious, Flux, etc. 

The solution would probably be to allow the user to set the sample resolution, CFG, sampling steps, etc. just as if it were a regular generator. Right now these are completely hardcoded in Lines 5248-5257 of train_util.py - 30 steps, 512x512, 7.5 CFG, doesn't even display a seed, and while you can set a prompt (via a text file only... probably should be enterable here too), there's no way to also enter a negative prompt that I'm aware of.

Some extra sample types would be nice as well - I tend to stick to DPM++ 3M SDE Karras, and that's not even selectable at all.

**Comment by derrian-distro** [comment]
those are all set via the sample args at the bottom and including the correct syntax as described [here](https://github.com/darkstorm2150/sd-scripts?tab=readme-ov-file#generating-sample-images)

**Comment by Jelosus2** [comment]
I'll close this issue as it seems to be solved. If it isn't then feel free to open another issue. PD: don't relly too much on the sampling from trainers. Is good to get a general idea but you should always test on your webui of choice.
