### ISSUE TITLE
Installing issues?

### ISSUE THREAD

**Issue by Sorry-Im-Stupid** [derrian-distro/LoRA_Easy_Training_Scripts#256]
I'm trying to install on linux using the shell script, and it keeps telling me it's putting it in 'stdout' and that the install file is not present. 
It is indeed not present in the folder it's supposed to be in, and I can't tell why.

`
sh -c "$(wget https://raw.githubusercontent.com/derrian-distro/LoRA_Easy_Training_Scripts/main/install310.sh -O -)"
--2024-11-12 18:58:26--  https://raw.githubusercontent.com/derrian-distro/LoRA_Easy_Training_Scripts/main/install310.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35 [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]      35  --.-KB/s    in 0s      

2024-11-12 18:58:26 (2.20 MB/s) - written to stdout [35/35]

python3.10: can't open file '/home/USERNAME/Stable/Lora-trainer/install.py': [Errno 2] No such file or directory
`

**Comment by Jelosus2** [comment]
If that doesn't work you can clone the repository with git and run the shell file that's included

**Comment by Sorry-Im-Stupid** [comment]
Yeah I'll have to do that today, but this is still a potential problem for anyone who can't do the long way.

**Comment by Jelosus2** [comment]
So far we had no more reports about this issue and it's been faily a long time. If more reports come in we would need to look into it

**Comment by Sorry-Im-Stupid** [comment]
I've gone through the manual mode and it did install, but now the program won't start. When I try to run the .sh script I get this:

`qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, vkkhrdisplay, minimalegl, vnc, minimal, xcb, wayland, linuxfb, offscreen, wayland-egl.

/home/USERNAME/Stable/Lora-trainer/LoRA_Easy_Training_Scripts/run.sh: line 4: 13925 Aborted                 (core dumped) python main.py
`

**Comment by Sorry-Im-Stupid** [comment]
In the application folder I assume? Or a subfolder?

**Comment by Sorry-Im-Stupid** [comment]
Oh yeah. 
Ok, that worked! Thank you.

**Comment by Jelosus2** [comment]
Great!

**Comment by Sorry-Im-Stupid** [comment]
Now I just have to figure out how to make a LoRA with it, and hope 16gb is enough Vram for the one I want to make.

**Comment by Jelosus2** [comment]
Depends on the base model but 16gb vram is enough even on flux. Also I hope that the GPU is a Nvidia one lol
