### ISSUE TITLE
Usability and the Tooltips

### ISSUE THREAD

**Issue by Sorry-Im-Stupid** [derrian-distro/LoRA_Easy_Training_Scripts#257]
In the almost a week since I got this program I've done a fair amount of experimenting, trying to make a style lora with mixed but mostly disappointing results.
I haven't achieved what I want, but I have noticed some patterns in the process which eventually led me to some information that should have been in the manual, or at least in the tooltips. if there is a manual I haven't seen it anyway.

Most recent revelation: The face crop augment range is not how many pixels _around_ the face to crop. Why is the default value for face crop 1 pixel? No wonder the style lora I was making was messing up the faces, it would detect a face and then crop out 1 pixel of it. Feels like the tooltip should explain this.

Now I'm hoping for a new revelation about the hands problem next.
Does anybody have similar experience to share with regards to usability ideas?

**Comment by derrian-distro** [comment]
honestly, I have never once used face crop, nor was I very interested in finding out, so I just went with what I believed was correct. I don't intend to update the tooltips, however, as a very large majority of the settings in this UI i've never actually used myself

**Comment by Sorry-Im-Stupid** [comment]
Is there any way of adding an automatic hand and foot detection function?
In attempting to correct the messy hands issue I've done it manually and the results are significant. But it is a very tedious process to do it that way.

**Comment by Jelosus2** [comment]
You mean for cropping them like face crop?

**Comment by Sorry-Im-Stupid** [comment]
Yeah. There has to be a way to get the model to recognize hands and crop them like they do faces. Should theoretically be able to do the same for every body part, really. I wonder if that would be the nay to permanently fix the whole three arms problem. Or six finger, two thumbs... I see it a lot less lately but every so often you still get it.

**Comment by Jelosus2** [comment]
It's possible but sd_scripts, which are the ones used for training, doesn't have them implemented, only for faces.

**Comment by Jelosus2** [comment]
Since there isn't anything else to discuss here I'll close the issue. If you want those kind of features you should make a request in the repository of sd-scripts
