### ISSUE TITLE
trainer won't start, ModuleNotFoundError: No module named 'triton'

### ISSUE THREAD

**Issue by Zsnack** [derrian-distro/LoRA_Easy_Training_Scripts#263]
Hi there, trying to run this project. I have a fresh install, but when I click on start.bat, I get the following error: 

```
F:\New Folder\dif2\ComfyUI_windows_portable\Training\LoRA_Easy_Training_scripts_Backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
F:\New Folder\dif2\ComfyUI_windows_portable\Training\LoRA_Easy_Training_scripts_Backend\sd_scripts\venv\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "F:\New Folder\dif2\ComfyUI_windows_portable\Training\LoRA_Easy_Training_scripts_Backend\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
F:\New Folder\dif2\ComfyUI_windows_portable\Training\LoRA_Easy_Training_scripts_Backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
```

Then it freezes there. 

Afaik from my googling, there doesn't seem to be a problem with triton itself but something else that is going wrong internally. Any advice?

**Comment by Jelosus2** [comment]
Theres no such file as `start.bat`.

**Comment by Jelosus2** [comment]
Ah that's normal. It shows that but it won't start training until you hit the start training button.

**Comment by Zsnack** [comment]
> Ah that's normal. It shows that but it won't start training until you hit the start training button.

ah gotcha. Though is it normal for it to freeze at the last line that I pasted? I can't get the application to even open, let alone start training :\

**Comment by Jelosus2** [comment]
No, that's not normal. It should open a UI

**Comment by Jelosus2** [comment]
Yea, that's normal. Could you try installing it on another drive?

**Comment by Zsnack** [comment]
Figured it out! I believe the issue was the space in "New Folder" in my directory path. It's given me a few problems before when it comes to python related stuff. Trainer opens as normal when it's installed in another directory without a space in it.
