### ISSUE TITLE
Question regarding Sample ARGS

### ISSUE THREAD

**Issue by wongex23** [derrian-distro/LoRA_Easy_Training_Scripts#265]
Hi all,

I would like to know if we can use "SEED" for the SAMPLE ARGS part?

I want to use "SEED" to force all generated sample pics are in the same pattern / style for better comparison.

Thank you in advance!

**Comment by derrian-distro** [comment]
https://github.com/darkstorm2150/sd-scripts?tab=readme-ov-file#sample-image-generation-during-training
this explains all of the options you can set in the sample file, in this case you would want to add --d <seedNum> to every prompt
