### ISSUE TITLE
Python version when installing

### ISSUE THREAD

**Issue by WesleyNery** [derrian-distro/LoRA_Easy_Training_Scripts#29]
So, I was having some problems and it was because of the python version. 
On the installer you do check for python 3.10 via registry, but then you just call 'python' to create the venv. if the version o the PATH is not the 3.10 (which can happen, was my case) it will install with the wrong version.

**Comment by derrian-distro** [comment]
I actually don't check anymore because that was too unreliable, too many people had 3.10 installed but was not detected by my scripts, so now the scripts do no checking at all.
