### ISSUE TITLE
No files under sd_scripts folder through git clone

### ISSUE THREAD

**Issue by watermelon-juice-maker** [derrian-distro/LoRA_Easy_Training_Scripts#30]
Hello,

Not sure why I get an empty sd_scrpts folder after I git clone your script on Colab or Paperspace . This only happened after the recent updates.

Is there a fix for it or am I doing something wrong here?

Many thanks.

**Comment by watermelon-juice-maker** [comment]
Add --recursive after git clone fixed the problem.

**Comment by derrian-distro** [comment]
yes, the --recursive is required because sd_scripts and locon are submodules. glad you figured it out
