### ISSUE TITLE
Installation error locon repo moved

### ISSUE THREAD

**Issue by Blackened15** [derrian-distro/LoRA_Easy_Training_Scripts#33]
seems the locon https://github.com/KohakuBlueleaf/LoCon moved, so install gives fatal error. Path doesn't seems to be inside the installer bat file, so cant fix it myself easily.

**Comment by derrian-distro** [comment]
yep, kohaku renamed the repo to LyCORIS, to support the new method of training that was added, I will be fixing it soon

**Comment by derrian-distro** [comment]
alright, I just finished updating the scripts to support the new repo as well as everything added in it. you should be able to install through the same installer

**Comment by Blackened15** [comment]
Keep getting this error, with both popup and command line, seems a part of the process can't find my training image but it can clearly list them earlier

`Starting command_line training...
F:\training\amc2
00000-0-20230225_161639.png
00001-0-20230225_161652.png
00002-0-20230225_161728.png
00003-0-20230225_161804.png
00004-0-20230225_161812.png
00005-0-20230225_161816.png
00006-0-20230225_161820.png
Created a txt file named last.txt in the output folder
prepare tokenizer
update token length: 150
Use DreamBooth method.
prepare images.
0 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 320
  max_bucket_reso: 960
  bucket_reso_steps: 64
  bucket_no_upscale: False


[Dataset 0]
loading image sizes.
0it [00:00, ?it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
F:\apps\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
F:\apps\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォル ダではなく、画像があるフォルダの親フォルダを指定する必要があります）
Press any key to continue . . .`
