### ISSUE TITLE
No matching distribution found for tensorflow==2.10.1

### ISSUE THREAD

**Issue by witfyl-ravped** [derrian-distro/LoRA_Easy_Training_Scripts#35]
I was having issues with my default 3.10.10 Python version. So I downgraded to 3.10.6 per your instructions. However now I get the following when running `pip install --upgrade -r requirements.txt`:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.10.1
```

Clearly the two are compatible, why might I be getting this error?

**Comment by derrian-distro** [comment]
not sure, probably should just delete the venv and create it from scratch, this sounds like an sd-scripts issue however

**Comment by witfyl-ravped** [comment]
Thanks, indeed I had to modify this to instill `tensorflow-macos` on my machine

**Comment by gate3** [comment]
> tensorflow-macos

@witfyl-ravped I'm running into this same issue currently, 
1. Did you change from tensorflow to tensorflow-macos in requirements.txt
2. did you need to change anything else
