### ISSUE TITLE
Ask for folders when loading json

### ISSUE THREAD

**Issue by trihardseven** [derrian-distro/LoRA_Easy_Training_Scripts#36]
So the old version I was using always asked for folders and lora name when using a json file. Now it just goes directly to training. Is there a way to make it ask again? I like using a single json for everything.

**Comment by derrian-distro** [comment]
I can add an option sure, I removed it originally because people were complaining about it, but I can very easily make it work.

**Comment by trihardseven** [comment]
I'd appreciate it. At least for folders and name, the rest can be automatic
