### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute

### ISSUE THREAD

**Issue by Ketorami** [derrian-distro/LoRA_Easy_Training_Scripts#4]
Ahh , I've been testing and coming up with a solution all day. I really haven't found a solution.Do you have any suggestions?

![Screenshot 2023-01-23 024743](https://user-images.githubusercontent.com/101268214/213937027-d10b0e0e-4e61-40c7-be3b-94f6474f00b6.png)

**Comment by derrian-distro** [comment]
I am almost done with the update to fix this, just doing some final testing, will be out within the hour.

**Comment by derrian-distro** [comment]
update has been released make sure to git pull to update.
