### ISSUE TITLE
Documentation - what is the intended way to continue training? 

### ISSUE THREAD

**Issue by BRRussell** [derrian-distro/LoRA_Easy_Training_Scripts#41]
The readme currently says: 

lora_model_for_resume 	str 	NO 	Loads a "Hypernetwork" into the training model, also works for LoRA, which is why I have it here, this is not the intended way to continue training though

I can't find anywhere else what the intended way of continuing training is. Is that an available thing to do? 

Thank you!

**Comment by derrian-distro** [comment]
save_state and resume, which are also in the args list

**Comment by uwidev** [comment]
Set `resume` to the directory of your saved checkpoint(?). This assumes you have `save_state` true and set it up correctly. Your epochs will restart from 0, so take that into account when doing additional training.
