### ISSUE TITLE
Command line training broken - KeyError

### ISSUE THREAD

**Issue by amarney4862** [derrian-distro/LoRA_Easy_Training_Scripts#42]
As of the newest update, only the popup script is working - running the command line script gives the below error. This looks to be a bug in one of the new args set up. I did go through my ArgsList.py and ensure everything relating to loading a json was disabled.

```
Starting command_line training...
updating LyCORIS if needed...

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "F:\LoRA_Easy_Training_Scripts\main.py", line 148, in <module>
    main()
  File "F:\LoRA_Easy_Training_Scripts\main.py", line 63, in main
    json_path = pre_args.load_json_path if pre_args.load_json_path else args['load_json_path']
KeyError: 'load_json_path'
Press any key to continue . . .
```

**Comment by derrian-distro** [comment]
did you remove them? removing them will break the code. they are variables that must exist, just set them to None if you don't want to use them

**Comment by amarney4862** [comment]
No. They were set to "None."

**Comment by amarney4862** [comment]
Could this be because I don't have a json folder set somewhere? I don't see the point of using it, so I don't have one. Perhaps it shouldn't give a fatal error if this isn't set, and should just skip over it? It's no an essential part of training.

**Comment by derrian-distro** [comment]
It doesn't throw any errors if it isn't set, I don't have it set usually. The multi_run arg is for queues, and I don't usually queue things.

I've also had exactly 0 errors regarding the json code, so it is likely that you modified something, unintentionally most likely, and it is causing issues.

**Comment by amarney4862** [comment]
Looks like the newest version of the installer you uploaded has the args necessary for it to work.
