### ISSUE TITLE
[Feature Request] Min-SNR Weighting Strategy

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [derrian-distro/LoRA_Easy_Training_Scripts#45]
I have no idea if this will be affecting lora training, but kohyas trainer just merged/added this https://github.com/kohya-ss/sd-scripts/pull/308 .
Might have some potential for even better/more efficient training?

**Comment by derrian-distro** [comment]
already on it, probably won't be done until tomorrow though, I don't have time right this moment

**Comment by derrian-distro** [comment]
update pushed, going to close this comment now
