### ISSUE TITLE
LoCon training set by lyco or locon in JSON?

### ISSUE THREAD

**Issue by uwidev** [derrian-distro/LoRA_Easy_Training_Scripts#46]
When running prompt and selecting to train LoCon, as per docs(?), `locon` isn't set inside of the JSON file saved. Instead, it seems there's a different value being set, `lyco`. It also sets the `network_args`'s `algo` to be `lora`, which is a bit strange, considering this is for LoCon. For LoHa it's set to `loha`. 

However, on the docs, it says that for LoCon training, `locon` needs to be set in the config to true. So which one is it? Is there a difference between the two? Do they do the same thing?

**Comment by derrian-distro** [comment]
the lyco variable handles that, the locon variable is legacy and deprecated, thanks for pointing that out, I guess I forgot to update the readme, I'll push that out in the next update
