### ISSUE TITLE
ModuleNotFoundError: No module named 'xformers'

### ISSUE THREAD

**Issue by yuuyuublog** [derrian-distro/LoRA_Easy_Training_Scripts#48]
I got an error when I launch runpopup.bat, 

↓↓
ModuleNotFoundError: No module named 'xformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\LoRA_Easy_Training_scripts\LoRA_Easy_Training_Scripts\main.py", line 148, in <module>
    main()
  File "C:\Users\user\Desktop\LoRA_Easy_Training_scripts\LoRA_Easy_Training_Scripts\main.py", line 81, in main
    train_network.train(args)
  File "C:\Users\user\Desktop\LoRA_Easy_Training_scripts\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 151, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "C:\Users\auser\Desktop\LoRA_Easy_Training_scripts\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\library\train_util.py", line 1716, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "C:\Users\user\Desktop\LoRA_Easy_Training_scripts\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\library\train_util.py", line 1764, in replace_unet_cross_attn_to_xformers
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです

I installed xformers, "python -m xformers.info" says like this

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xFormers 0.0.18
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.flshattF:               available
memory_efficient_attention.flshattB:               available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        unavailable
memory_efficient_attention.tritonflashattB:        unavailable
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               False
is_functorch_available:                            False
pytorch.version:                                   2.0.0+cu118
pytorch.cuda:                                      available
gpu.compute_capability:                            7.5
gpu.name:                                          NVIDIA GeForce GTX 1660 Ti
build.info:                                        available
build.cuda_version:                                1108
build.python_version:                              3.10.10
build.torch_version:                               2.0.0+cu118
build.env.TORCH_CUDA_ARCH_LIST:                    5.0+PTX 6.0 6.1 7.0 7.5 8.0 8.6
build.env.XFORMERS_BUILD_TYPE:                     Release
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   wheel-v0.0.18
source.privacy:                                    open source

How can I solve this?

**Comment by derrian-distro** [comment]
did you install through my installer? the installer installs everything you need for the program

**Comment by yuuyuublog** [comment]
yes, I used "installers v6"

I can train by changing xformers false in config.json. 
I cannot use only xformers

**Comment by derrian-distro** [comment]
hmm, interesting, xformers should have installed fine, as I haven't had any issues with the installers on that end, can you run the torch_update.bat and follow what it asks you? it will rebuild the venv for you and might make things work for you

**Comment by yuuyuublog** [comment]
I launch torch_update.bat and I select 2.0.0.

And "ModuleNotFoundError: No module named 'xformers" is gone but new error happen.

↓↓
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

my torch and cuda version is here.
↓
python -c "import torch; print( torch.__version__ )"
2.0.0+cu118

**Comment by derrian-distro** [comment]
What graphics card do you have? I've gotten reports that 2060's can't use torch 2

**Comment by yuuyuublog** [comment]
I use GTX1660Ti

**Comment by derrian-distro** [comment]
I don't believe 1660ti are compatible with torch 2 either, I suggest running the update torch bat again and downgrading to torch 1.12.1. That being said, you will likely struggle to train as 6gb cards are the absolute minimum for training lora. It is likely you won't be able to train locon or loha, or use the d-adaption scheduler either.

**Comment by yuuyuublog** [comment]
I downgrade to torch 1.12.1 and all error is gone! 
I could use xformers.

Thank you very much for helping me!

**Comment by derrian-distro** [comment]
it's no problem, some cards just don't like torch 2, unfortunately, big reason why I kept in the original torch version
