### ISSUE TITLE
When merging loras, weight shouldn't be limited from 0 to 1.

### ISSUE THREAD

**Issue by lendrick** [derrian-distro/LoRA_Easy_Training_Scripts#52]
Is the value being clamped somewhere?  I've got a weak LoCon that I'd like to merge at a weight higher than 1.  I also can think of at least one use case for merging at a negative weight (such as making the output of a model brighter by merging in the contrast lora at a negative value).

**Comment by derrian-distro** [comment]
when I made the script the merge script had a hard limit of 0 -> 1, I believe that was lifted so I can quickly make a change for that. I was clamping it because of this limitation, (which would just error if I didn't)
