### ISSUE TITLE
How should I setup/name my training images directory ?

### ISSUE THREAD

**Issue by by321** [derrian-distro/LoRA_Easy_Training_Scripts#53]
I got this error: Please verify arguments (train_data_dir must be the parent of folders with images)

After searching the internet, it seems I need to put images in a subdirectory, named something like "100_jimmy", under the directory I selected in the GUI. I did that and now it started training. But, how should I pick that number, and is jimmy going to be the class name or trigger word for my images/Lora ?

**Comment by derrian-distro** [comment]
the 100_ is the number is the number of times the images repeat, 100 is likely far too many, I usually only do 1 or 2, or slightly more with a very small dataset. The name of the folder means nothing so long as you have txt files for the images as kohya doesn't actually have class names or trigger words.

**Comment by superskirv** [comment]
I am confused about the data structure. This is my current file structure:

\Lora\LoRA_Easy_Training_Scripts\training\data\[project]\01.png
\Lora\LoRA_Easy_Training_Scripts\training\data\[project]\01.txt

Where should this [num]_project folder be? and what files should be inside, png and txt?
