### ISSUE TITLE
[Question] What is mwxKTEtelILoIbMbruuM.zip for and why hosted on odd website?

### ISSUE THREAD

**Issue by TFWol** [derrian-distro/LoRA_Easy_Training_Scripts#54]
If it's cudnn, why not get it from nvidia's dev site?

**Comment by derrian-distro** [comment]
it is cudnn, and nvidia requires to to set up a developer account to download it. up to you if you want to download and install it manually, but I don't know how I'd be able to make it painless to install while also changing the download to nvidia proper.

**Comment by TFWol** [comment]
Ah, I see.

Well, I usually get it from nvidia directory if that helps (no account needed this way):
https://developer.download.nvidia.com/compute/redist/cudnn/v8.6.0/local_installers/11.8/

**Comment by derrian-distro** [comment]
that is great, I will make the switch immediately, I was unable to find a way to download it without forcing an account, so this is very helpful, thank you for telling me

**Comment by TFWol** [comment]
No problem!
I had stumbled across the links while periodically trying to find the latest tips and tricks. It's a pain to find gems among all the noise.

Here's a post with good info:
https://www.reddit.com/r/StableDiffusion/comments/y71q5k/4090_cudnn_performancespeed_fix_automatic1111/
