### ISSUE TITLE
Replace CrossAttention.forward to use xformers

### ISSUE THREAD

**Issue by OneMinuteDeen** [derrian-distro/LoRA_Easy_Training_Scripts#55]
I am unable to use XFormers when training. I tried installing other torch versions, but this didn't help either. I am using a GTX 1070.

**Comment by derrian-distro** [comment]
did you install the 10 series patch that is provided in the installer? 10 series cards are old enough that they must use the patch to train. I also believe that only torch 1.12.1 works with the 10 series cards. beyond that, this would be an sd-scripts issue and I suggest you open up an issue there.

**Comment by OneMinuteDeen** [comment]
I installed 1.12.1 together with the 10 series patch, but I still get the message "Replace CrossAttention.forward to use xformers". I will open up an issue on the sd-scripts repo

**Comment by derrian-distro** [comment]
that message is saying that it is using xformers I believe, because I'm pretty sure everybody gets that message

**Comment by OneMinuteDeen** [comment]
I'm not sure about that. I've been training on google colab before, and there you certainly do not get this message

**Comment by derrian-distro** [comment]
I believe that is the difference between windows and linux

**Comment by derrian-distro** [comment]
according to kohya's code, the print statement of "Replace CrossAttention.forward to use xformers" is the message to denote that the CrossAttention.forward  is going to be replaced to use xformers, the scripts are working as intended. code below is the exact function run during training, which is used in the `train_network.py` file (the one used for training lora) on this line,  `train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)`

```python
def replace_unet_cross_attn_to_xformers():
    print("Replace CrossAttention.forward to use xformers")
    try:
        import xformers.ops
    except ImportError:
        raise ImportError("No xformers / xformersがインストールされていないようです")

    def forward_xformers(self, x, context=None, mask=None):
        h = self.heads
        q_in = self.to_q(x)

        context = default(context, x)
        context = context.to(x.dtype)

        if hasattr(self, "hypernetwork") and self.hypernetwork is not None:
            context_k, context_v = self.hypernetwork.forward(x, context)
            context_k = context_k.to(x.dtype)
            context_v = context_v.to(x.dtype)
        else:
            context_k = context
            context_v = context

        k_in = self.to_k(context_k)
        v_in = self.to_v(context_v)

        q, k, v = map(lambda t: rearrange(t, "b n (h d) -> b n h d", h=h), (q_in, k_in, v_in))
        del q_in, k_in, v_in

        q = q.contiguous()
        k = k.contiguous()
        v = v.contiguous()
        out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる

        out = rearrange(out, "b n h d -> b n (h d)", h=h)

        # diffusers 0.7.0~
        out = self.to_out[0](out)
        out = self.to_out[1](out)
        return out

    diffusers.models.attention.CrossAttention.forward = forward_xformers
```
