### ISSUE TITLE
ERROR: No matching distribution found for torch==2.1.0.dev20230320+cu118

### ISSUE THREAD

**Issue by DvST8x** [derrian-distro/LoRA_Easy_Training_Scripts#56]
Clean install since this looks like a big update.
I attempted to manually install other torch+cu versions but ran into other errors later.
When prompted for torch version I selected 2 = 2.1.0: 2

Windows 11 (25357.1)
AMD 5900X / 32GB / 4090 FE / M2 drives
_______________________________________________________________________

`D:\Programs\lora>git clone https://github.com/derrian-distro/LoRA_Easy_Training_Scripts
Cloning into 'LoRA_Easy_Training_Scripts'...
remote: Enumerating objects: 602, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 602 (delta 104), reused 161 (delta 63), pack-reused 386
Receiving objects: 100% (602/602), 26.40 MiB | 42.05 MiB/s, done.
Resolving deltas: 100% (342/342), done.

D:\Programs\lora>cd LoRA_Easy_Training_Scripts

D:\Programs\lora\LoRA_Easy_Training_Scripts>install.bat
Running on windows...
Python version 3.10 detected...
Git is installed... installing
Submodule 'LyCORIS' (https://github.com/KohakuBlueleaf/LyCORIS) registered for path 'LyCORIS'
Submodule 'sd_scripts' (https://github.com/kohya-ss/sd-scripts) registered for path 'sd_scripts'
Cloning into 'D:/Programs/lora/LoRA_Easy_Training_Scripts/LyCORIS'...
Cloning into 'D:/Programs/lora/LoRA_Easy_Training_Scripts/sd_scripts'...
Submodule path 'LyCORIS': checked out '8b47a5349b59efac812664c5732c6e3947a6fec7'
Submodule path 'sd_scripts': checked out 'c924c47f374ac1b6e33e71f82948eb1853e2243f'
setting execution policy to unrestricted
creating venv and installing requirements
which version of torch do you want to install?
0 = 1.12.1
1 = 2.0.0
2 = 2.1.0: 2
installing torch
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.1.0.dev20230320+cu118 (fromversions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0.dev20230324+cu118, 2.1.0.dev20230325+cu118, 2.1.0.dev20230326+cu118, 2.1.0.dev20230327+cu118, 2.1.0.dev20230328+cu118, 2.1.0.dev20230329+cu118, 2.1.0.dev20230330+cu118, 2.1.0.dev20230331+cu118, 2.1.0.dev20230401+cu118, 2.1.0.dev20230402+cu118, 2.1.0.dev20230403+cu118, 2.1.0.dev20230404+cu118, 2.1.0.dev20230405+cu118, 2.1.0.dev20230406+cu118, 2.1.0.dev20230407+cu118, 2.1.0.dev20230408+cu118, 2.1.0.dev20230409+cu118, 2.1.0.dev20230410+cu118, 2.1.0.dev20230411+cu118, 2.1.0.dev20230412+cu118, 2.1.0.dev20230413+cu118, 2.1.0.dev20230414+cu118, 2.1.0.dev20230415+cu118, 2.1.0.dev20230416+cu118, 2.1.0.dev20230417+cu118, 2.1.0.dev20230418+cu118, 2.1.0.dev20230419+cu118, 2.1.0.dev20230420+cu118, 2.1.0.dev20230421+cu118, 2.1.0.dev20230422+cu118, 2.1.0.dev20230423+cu118, 2.1.0.dev20230424+cu118, 2.1.0.dev20230425+cu118, 2.1.0.dev20230426+cu118, 2.1.0.dev20230427+cu118, 2.1.0.dev20230428+cu118, 2.1.0.dev20230429+cu118, 2.1.0.dev20230430+cu118, 2.1.0.dev20230501+cu118, 2.1.0.dev20230502+cu118, 2.1.0.dev20230503+cu118, 2.1.0.dev20230504+cu118, 2.1.0.dev20230505+cu118, 2.1.0.dev20230506+cu118, 2.1.0.dev20230507+cu118, 2.1.0.dev20230508+cu118, 2.1.0.dev20230509+cu118, 2.1.0.dev20230510+cu118, 2.1.0.dev20230511+cu118, 2.1.0.dev20230512+cu118, 2.1.0.dev20230513+cu118, 2.1.0.dev20230514+cu118, 2.1.0.dev20230515+cu118, 2.1.0.dev20230516+cu118, 2.1.0.dev20230517+cu118, 2.1.0.dev20230518+cu118, 2.1.0.dev20230519+cu118, 2.1.0.dev20230520+cu118, 2.1.0.dev20230521+cu118, 2.1.0.dev20230522+cu118)
**ERROR: No matching distribution found for torch==2.1.0.dev20230320+cu118**
Traceback (most recent call last):
  File "D:\Programs\lora\LoRA_Easy_Training_Scripts\installer\installer.py", line 163, in <module>
    main()
  File "D:\Programs\lora\LoRA_Easy_Training_Scripts\installer\installer.py", line 70, in main
    subprocess.check_call(f"{python} install {torch_version}".split(" "))
  File "C:\Program Files\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['venv\\Scripts\\pip.exe', 'install', 'torch==2.1.0.dev20230320+cu118', 'torchvision==0.16.0.dev20230320+cu118', '--extra-index-url', 'https://download.pytorch.org/whl/nightly/cu118']' returned non-zero exit status 1.
Press any key to continue . . .`

**Comment by derrian-distro** [comment]
Ah of course, torch 2.1.0 was experimental when I created the installer, that dev version must not exist anymore, I'll remove it from the options and instead put an option for torch 2.0.1, which is stable.

**Comment by derrian-distro** [comment]
Updated the installer to replace torch 2.1.0 with 2.0.1
