### ISSUE TITLE
I have 4G vram and got torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by dajusha** [derrian-distro/LoRA_Easy_Training_Scripts#59]
Is there any way to add arguments like _--medvram_ in webui?

**Comment by derrian-distro** [comment]
no, there is no way to train on a 4gb card unfortunately, the minimum I know can work is 6gb and that is with a bunch of odd settings.

**Comment by Sorry-Im-Stupid** [comment]
I have 16GB and I keep getting `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU `
With all the optimizations I can find it still isn't enough by apparently 20MiB!

**Comment by Jelosus2** [comment]
On what are you training
