### ISSUE TITLE
RuntimeError: Internal C++ object (PySide6.QtWidgets.QWidget) already deleted.

### ISSUE THREAD

**Issue by IronWimpy** [derrian-distro/LoRA_Easy_Training_Scripts#61]
Receiving error 

RuntimeError: Internal C++ object (PySide6.QtWidgets.QWidget) already deleted.

After deleting a subset, adding a new one and then deleting the new one. This will then disable the ability to add or delete new subsets.

On a fresh config, receiving error

starting validation of args...
starting validation of dataset_args...
failed validation

Despite pointing to the correct subdirectory. Tested on multiple directories.

Dependencies 
PySide6                      6.5.1
PySide6-Addons               6.5.1
PySide6-Essentials           6.5.1

This is on a fresh pull, ran update.bat and install.bat

Same error occurs after manually editing the TOML config and reloading

**Comment by derrian-distro** [comment]
what system are you running on, windows?

this is an error I haven't had, nor think I can reproduce. however I'll try and figure out what may be happening, do you have the stack trace?

**Comment by derrian-distro** [comment]
hmm, after looking at my install, I realize that I'm still on pyside6 6.5.0, I will have to update the installation bat to install that version as it works fine on that version

**Comment by derrian-distro** [comment]
alright, update pushed, make sure to run the update.bat at least once *after* you git pull or run the existing update.bat

**Comment by IronWimpy** [comment]
Works! Thanks for your hard work!

**Comment by derrian-distro** [comment]
no problem, it was an easy fix
