### ISSUE TITLE
[Feature Request] Save toml and tag occurrences by default

### ISSUE THREAD

**Issue by Radtoo** [derrian-distro/LoRA_Easy_Training_Scripts#63]
I suggest saving the toml configuration and maybe tag_occurrence_txt_file to the output directory by default, with a checkbox to disable this behavior.

These are easy to delete even if they were generated when they are ultimately not needed but annoying if you forgot to save them at the right moment while queueing variant sets.

**Comment by derrian-distro** [comment]
I can probably do that, it would also give me more of a reason to re-implement the tag occurrence file too. I'll add it to the list of things to do

**Comment by Radtoo** [comment]
If the tag occurrence was removed and is difficult to (re-)implement, I'd still suggest changing the .toml settings to be saved in the output folder by default with a checkbox to disable (maybe under "saving args"). Better it gets saved unless specified otherwise. Thanks either way!

**Comment by derrian-distro** [comment]
whoops, closed the wrong one

**Comment by derrian-distro** [comment]
I implemented the tag occurrence file as well as outputting a toml file on train, These are *not* on by default however. you can find them in the saving args dropdown
