### ISSUE TITLE
class_tokens missing

### ISSUE THREAD

**Issue by hashms0a** [derrian-distro/LoRA_Easy_Training_Scripts#67]
Is it possible to pass class_tokens to the TOML file by adding them to the UI?

**Comment by derrian-distro** [comment]
I didn't add it to the ui because, as far as I know, the class tokens don't mean anything when you provide it a caption file. I'd have to look at the implementation of it to see if it's worth adding, because I have a feeling that it would just introduce confusion and not be that useful.

**Comment by hashms0a** [comment]
Understood.
