### ISSUE TITLE
Broken UI (Checkboxes don't appear)

### ISSUE THREAD

**Issue by hectormaximillian** [derrian-distro/LoRA_Easy_Training_Scripts#68]
Hello, I'm ran a fresh install BUT the Ui are broken, the checkboxes are working fine, but when I click it, it shows nothing, even though the checkboxes appear to work, what am I missing?

![borked](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/50435379/f46ae494-b384-4169-bd88-eadcf9f1a491)

**Comment by derrian-distro** [comment]
What os are you running? This might be an issue with the themeing. If it is, I can add a "no theme" mode which removes the theme all together, hopefully without requiring a restart

**Comment by hashms0a** [comment]
The themes are working fine on Kubuntu. Check that all the libraries, modules, and packages in requirements_ui.txt are installed correctly.

**Comment by jexom** [comment]
Windows 10, fresh install from commit cc96415, same isuue
![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/6067696/08af625d-2240-42f2-8c34-d8620712b44e)
