### ISSUE TITLE
Select external VAE

### ISSUE THREAD

**Issue by allo-** [derrian-distro/LoRA_Easy_Training_Scripts#69]
It seems there is no option to load a VAE if the model doesn't have a baked VAE.

**Comment by derrian-distro** [comment]
I didn't include it because I didn't really see much of a reason to, I've only encountered heavy baking when training with an external VAE so I assumed nobody uses it. That being said, I wouldn't train on a mix anyways

**Comment by allo-** [comment]
I only saw preview images that are greyish and know that it can make a difference when using textual inversion. When you say it's better not to use one or a model that requires one, I close here.
