### ISSUE TITLE
(feature request) Multiple Bookings for LoRA Training

### ISSUE THREAD

**Issue by mimimi999** [derrian-distro/LoRA_Easy_Training_Scripts#7]
The pop-up version of the file you provide is very convenient, so I'm using it.

I'm satisfied with the current situation, but LoRA training itself ends very quickly, so I thought it would be convenient if there was a multiple reservation function for training.

For example, the last confirmation in the pop-up asks, "Would you like to book your next training?"

If you select YES, the pop-up item will return to the beginning, and training B will be scheduled,
Start the set training when NO is selected.

(It may be possible to change the settings a little, but I don't have any programming knowledge, so I don't even know if it's possible.)

I would appreciate it if you could check it once.

**Comment by derrian-distro** [comment]
that's a great Idea, I'll look into adding it, shouldn't be hard for popup.py, might be harder for command_line.py but I'll figure it out.

**Comment by derrian-distro** [comment]
Hey mimimi999, I have implemented your request into the project, hope you enjoy using it! give me a shout if you have any issues with it.

**Comment by mimimi999** [comment]
I tested it and the training reservation feature works perfectly.
your work is great!
