### ISSUE TITLE
Dropout Error on LoHa training

### ISSUE THREAD

**Issue by Kaharos94** [derrian-distro/LoRA_Easy_Training_Scripts#74]
Trying to train a LoHa , it throws the error: 
`File "C:\Users\Mike\stablediffclone\Loratraining\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\lycoris\kohya.py", line 26, in create_network
    dropout = float(kwargs.get('dropout', 0.))
TypeError: float() argument must be a string or a real number, not 'NoneType'`

Maybe something in the lycoris repo changed?

**Comment by derrian-distro** [comment]
I don't actually have support for the dropout from lycoris. I didn't add it mainly because I forgot it existed. Nobody trains loha really. I'll probably add it in the next update, along with cp decomposition. Because I forgot about that one as well.

**Comment by Kaharos94** [comment]
yeah- fixed it on my local install by just giving it a set value in the script. guess you found the one guy who does,  turns out it's working out quite nice if you have a bunch of concepts you don't want to mix.

**Comment by ashllay** [comment]
> yeah- fixed it on my local install by just giving it a set value in the script. guess you found the one guy who does, turns out it's working out quite nice if you have a bunch of concepts you don't want to mix.

Can you tell how you have fixed it?

**Comment by derrian-distro** [comment]
I made some changes in the last update that should have fixed the issue. I'm going to close the commit now
