### ISSUE TITLE
[FEATURE] lion8bit support?

### ISSUE THREAD

**Issue by gLenahan** [derrian-distro/LoRA_Easy_Training_Scripts#76]
Any chance we could set support for lion8bit? sd-scripts has supported it for a while now and in the old versions of the easy training scripts you could use it. Lion8bit requires bitsandbytes over 0.38.0 but it shouldn't be an issue as I've been using 0.38.1 and have had zero issues with training.

**Comment by derrian-distro** [comment]
I'll think about adding it, I didn't up to now because I was unsure of if it was going to cause issues.

**Comment by derrian-distro** [comment]
after doing some research, bitsandbytes 0.38.1 or above *does* cause issues for windows, as such, I will not be adding support for lion8bit.
