### ISSUE TITLE
Installing stalls at Torch Install selection.

### ISSUE THREAD

**Issue by ssjgokillo** [derrian-distro/LoRA_Easy_Training_Scripts#80]
I'm not sure what I'm doing wrong here. I have Python 3.10.6 installed. When I run the install.py file everything works until I get to the section where it asks which version of Torch I want to install. Following the guide, I choose 2.1.0, then the command window gets filled with red text before closing automatically. Any ideas?

**Comment by derrian-distro** [comment]
Are you following the install instructions written on the Readme? The installers in the releases are deprecated, and you must install following the way outlined.

**Comment by jexom** [comment]
The install instructions for windows say to runt the installer bat and when you do that it asks to choose the torch version
