### ISSUE TITLE
Trained LORA not working

### ISSUE THREAD

**Issue by hienhocmo** [derrian-distro/LoRA_Easy_Training_Scripts#85]
I have used this script to train five times, but each time it seems that Lora is not the right person I trained. I included Lora in the prompt and used the trigger behind the underscore. Could you please share your successfully trained TOML on the latest version so that I can test it out?

**Comment by popedead** [comment]
Hello, I was doing a lot of tests and I received a little different results but generally good, don't forget to use description files together with your images

**Comment by derrian-distro** [comment]
there is generally speaking a ton of things that affect the way you train, the way you tag, the settings you train at, all of it. that being said, here is a template file that I have that is generally my training setup for training characters.
[default_template.zip](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/files/11775866/default_template.zip)

I should say though, just the training parameters isn't really enough to make a training good, tagging and dataset preparation are equally if not even *more* important
