### ISSUE TITLE
any idea on how to load settings from the config file?

### ISSUE THREAD

**Issue by Nthompson096** [derrian-distro/LoRA_Easy_Training_Scripts#87]
Wanted to load the settings from the program but I can't find a way to do so.

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/68661602/37a8b447-df2c-4d70-9d5b-b0419b4586a1)

**Comment by derrian-distro** [comment]
There's normally a bar at the top that states "file" you can load it there. But I don't see it, which is likely related to how your running it. The keyring ctrl+o should work to open up a file dialog

**Comment by Nthompson096** [comment]
Alright so it seems to try to load the file however I get hit with an error preventing me from loading it.
```
    args = args[self.name]['args']
TypeError: list indices must be integers or slices, not str
```

**Comment by Nthompson096** [comment]
Nvm looks like I loaded the wrong cfg file.
