### ISSUE TITLE
automatic WD14 tagging

### ISSUE THREAD

**Issue by moonshinegloss** [derrian-distro/LoRA_Easy_Training_Scripts#88]
it would be extremely nice if one could auto-tag the dataset and prefix the tags generated by WD14 before starting training (e.g. with a trigger word like "painting by sks" so all text files would start with it), since tagging is extremely important as mentioned in #85, an example of it can be found in the kohya gui fork: 

https://github.com/bmaltais/kohya_ss/blob/4f0e1f5f58b8cf292ff76cad2868730130303192/finetune/tag_images_by_wd14_tagger.py

WD14 generally does well even with real life pictures, not just anime, way better than alternatives too, but this could be expanded to other tagging wrappers.

thanks!

**Comment by derrian-distro** [comment]
I'll eventually get to it, tagging is generally a "backburner" type thing, because i'd like to get more of the training features built in, but I fully intend to implement a tagging system eventually. just don't expect it quickly

**Comment by moonshinegloss** [comment]
@derrian-distro would it be possible then to have a start and end hook that executes a user-defined e.g. bat scrip?

this would allow me and others to implement all sorts of great things, e.g. I could simply "outsource" the tagging to my own bat script that tags and then exits after; and thats when the easy training script would continue, could even check exit code if that's not too much, to abort the training.

and the "end hook" would be useful to notify e.g. on discord and other chats to know when some training finished, since many of us can't really do much while it's training

thanks!

**Comment by derrian-distro** [comment]
hmm, I might be able to setup something like that, Qt has a signal and slot system, so I can probably at some point implement a setup for that, but that comes later, I'd need to research how to set that up.

**Comment by moonshinegloss** [comment]
would it not be possible to just have two file location pickers in the UI, then call the scripts and wait to exit? one before training is supposed to start and one after training exited

**Comment by derrian-distro** [comment]
I'll think about it, it's not at the top of the list for me right now

**Comment by moonshinegloss** [comment]
@derrian-distro has this been implemented or closed because not planned? thanks

**Comment by derrian-distro** [comment]
closed because not planned
