### ISSUE TITLE
Icons don't appear

### ISSUE THREAD

**Issue by goodpies** [derrian-distro/LoRA_Easy_Training_Scripts#94]
What it sounds like. Icons don't show up so i have no idea if i've checked a box or not.

**Comment by fuyunekojima** [comment]
I suffer from the same symptoms.

**Comment by derrian-distro** [comment]
I don't know why that happens, it seems to be an issue with the system that is being used, as the icons show up for me. I can't exactly diagnose why it doesn't work, because, well, I don't run into the issue.

**Comment by GengroHirano** [comment]
Probably a PySide6 problem that occurs in a windows 10 64bit environment.
I don't know myself, but it seems that the svg used for the icons is not recognized properly.

I got around this by adding the following import.

file: LoRA_Easy_Training_Scripts\sd_scripts\venv\Lib\site-packages\qt_material\__init__.py

```python3
elif 'PySide6' in sys.modules:
    from PySide6.QtGui import (
        QFontDatabase,
        QAction,
        QColor,
        QGuiApplication,
        QPalette,
        QActionGroup,
    )
    from PySide6.QtWidgets import QColorDialog
    from PySide6.QtUiTools import QUiLoader
    from PySide6.QtCore import Qt, QDir
    from PySide6 import QtSvg, QtXml # ← add this.
```

| current | add import QtSvg, QtXml |
|:-:|:-:|
|![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/4410516/3b306ba2-1d0e-4496-9b3d-d73a23a16e5d)|![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/4410516/f1800388-6125-4d0a-877d-ce4896643b15)|

I really don't know why...

**Comment by darkzip** [comment]
@ [GengroHirano](https://github.com/GengroHirano)   

Thank you so much for posting the solution! I've got icons now.   

For others like me.
file: LoRA_Easy_Training_Scripts\sd_scripts\venv\Lib\site-packages\qt_material**\**__init_.py_
[__init__.py.txt](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/files/12343744/__init__.py.txt)

**Comment by Jelosus2** [comment]
Closing this because its pretty old and seems to be fixed already.
